Solução do desafio 12 em python.
OsProgramadores/op-desafios pull request #1019
Opened 2024-01-03 14:08 UTC by Lkzeu

Nesta solução eu foquei em tentar resolver o problema sem utilizar bibliotecas prontas.
Como a solução cita base 2, eu primeiro verifico se o número é par, depois desloco os bits para a direita enquanto conto quantas vezes este foi deslocado até chegar em 0x01.

Neste caso para verificar se o número em questão é base 2, eu desloco o 0x01  _counter_ bits para a esquerda, se o resultado for igual ao número lido, o número é base dois. No caso excepcional do número lido ser 1; vai entrar na condição dos pares, entretanto já será 0x01 e o contador 0 não será incrementado.

Todos os outros casos irão cair no print do caso ´false´

2024-01-07 04:25 UTC, mpinheir requested changes
@Lkzeu coloca por favor um README para explicar como funciona e como executar sua solução.

2024-01-07 04:26 UTC, mpinheir commented on desafio-12/Lkzeu/python/d12_potencia.py
> +    with open("d12.txt", "r") as f:
O que vai acontecer com sua aplicação se o d12.txt não existir? Trate esta possibilidade ao invés de deixar o progama abortar.

2024-01-20 15:34 UTC, Lkzeu commented on desafio-12/Lkzeu/python/d12_potencia.py
> +    with open("d12.txt", "r") as f:
Grato pelas sugestões! Agora o programa informa se o arquivo não existir e mostra uma mensagem mais amigável nesse caso. Caso ocorra algum outro erro na leitura do arquivo o programa vai mostrar o tipo de erro e a mensagem de erro que ocorreu.

2024-01-22 02:14 UTC, mpinheir approved these changes
LGTM

2024-01-22 02:14 UTC, merged