Desafio02 @maurilioSo
OsProgramadores/op-desafios pull request #1042
Opened 2024-04-08 03:08 UTC by maurilioSo

2024-04-09 03:14 UTC, magnussolidus commented
@maurilioSo por favor adicione uma descrição ao seu PR explicando o que o seu programa faz e o que alguém precisa fazer para executá-lo.

2024-04-09 04:19 UTC, mpinheir commented
@maurilioSo tua solução está exibindo o número 2. Note que o número 2 não é primo.
Coloque também por favor um Readme.md na solução para explicar como compilar e executar o programa.
Obrigado!

2024-04-09 15:55 UTC, magnussolidus commented on desafio-02/maurilioSo/java/PrimeNumbers.java
> +				if(num % i == 0) {
Sugestão: crie um método/função conforme os pontos a seguir:

- recebe o número atual como parâmetro
- verifica se o número recebido como parâmetro é primo
- retorna verdadeiro se o número for primo
- retorna falso se o número não for primo

Aí vc usa esse método para verificar se o teu número vai ou não ser exibido.

2024-04-09 15:55 UTC, magnussolidus commented on desafio-02/maurilioSo/java/PrimeNumbers.java
> +			if(test == 0) {
Seguindo a sugestão anterior, você não precisaria mais da variável `test` no seu código.

2024-04-09 15:55 UTC, magnussolidus commented on desafio-02/maurilioSo/java/PrimeNumbers.java
> +					test++;
Seguindo o método que falei, seu loop ficaria algo como:

`if (isPrimeNumber(num)) { System.out.println(num) }`

2024-04-09 15:55 UTC, magnussolidus commented on desafio-02/maurilioSo/java/PrimeNumbers.java
> +
A sua função/método para validar se o número é primo deve ficar fora da `main` e precisa ser estático (static).

2024-04-09 21:10 UTC, magnussolidus commented on desafio-02/maurilioSo/java/PrimeNumbers.java
> +		for (int i = 2; i <= 10000; i++) {
O desafio pede para começar do número 1.

2024-04-09 21:10 UTC, magnussolidus commented on desafio-02/maurilioSo/java/PrimeNumbers.java
> +	public static boolean isPrime (int num) {
O que acontecer aqui se entrar um número menor que 2? Se receber 1 ou 0 ele vai retornar que são primos.

2024-04-09 21:34 UTC, magnussolidus requested changes
Vou deixar o review como pedindo mudanças até a questão do pipeline ser solucionada. Pode seguir para o desafio 3 enquanto trabalhamos nisso.

2024-04-10 03:03 UTC, mpinheir commented
@maurilioSo bacana o README.

2024-04-14 03:26 UTC, maurilioSo commented
> @maurilioSo bacana o README.

Obrigado.

2024-04-14 03:57 UTC, mpinheir approved these changes
LGTM.

2024-04-14 03:57 UTC, mpinheir commented
@magnussolidus pode processar?

2024-04-14 18:55 UTC, magnussolidus approved these changes

2024-04-14 18:55 UTC, magnussolidus commented
> @magnussolidus pode processar?

Feito!

2024-04-27 01:14 UTC, merged