Desafio 03 - Codigo em JS para encontrar os números palindromos
OsProgramadores/op-desafios pull request #1058
Opened 2024-06-21 12:58 UTC by victorvssouza

Código em JS para encontrar os números palíndromos entre um intervalo determinado pelo usuário.

2024-06-22 03:23 UTC, MatMercer requested changes

2024-06-22 03:23 UTC, MatMercer commented on desafio-03/victorvssouza/javascript/main.js
> +main();
```suggestion
if (require.main === module) {
    main();
}
```

Em NodeJS é assim que fazemos uma main. Fora isso, o desafio está ok!

2024-06-23 20:49 UTC, magnussolidus commented on desafio-03/victorvssouza/javascript/main.js
> +main();
@victorvssouza Quando alguém abre uma issue você só marca ela quando resolvida nas seguintes circunstâncias:

1. A pessoa que solicitou as mudanças já revisou novamente o código e aprovou o PR.
2. A pessoa explicitamente falou que você pode fechar a issue.

Não é boa prática você mesmo marcar a issue como resolvida sem ser nesses casos acima; você espera uma nova revisão.

O que você deve fazer é solicitar o Review do seu código após fazer as alterações, mas mantenha as issues em aberto.

2024-06-24 01:10 UTC, MatMercer commented on desafio-03/victorvssouza/javascript/main.js
> +main();
OK!

2024-06-24 01:11 UTC, MatMercer approved these changes
Desafio OK!

2024-06-24 01:11 UTC, merged