Proposta de Solução desafio-02.
OsProgramadores/op-desafios pull request #1059
Opened 2024-06-22 02:56 UTC by ronaldofas

Segue minha proposta de solução ao desafio-02

2024-06-22 03:33 UTC, MatMercer requested changes
O programa está funcionando.

Altere o formato do Program.cs somente, tive problemas para rodar ele localmente

2024-06-22 03:33 UTC, MatMercer commented on desafio-02/ronaldofas/c#/primos/Program.cs
> +﻿ListarPrimos();
Use este formato para um programa que tem uma Main em .NET

```c#
using System;

class Program // é Program pois seu arquivo se chama Program.cs
{
    static void Main()
    {
        ListarPrimos();
    }
    ...
}
```

2024-06-22 03:33 UTC, MatMercer commented on op-desafios.sln
Remova esse arquivo

2024-06-22 14:19 UTC, ronaldofas commented on op-desafios.sln
Devo refazer o commit no meu fork e fazer um novo pull request?

2024-06-22 14:28 UTC, ronaldofas commented on op-desafios.sln
Esse arquivo não foi criado por mim, já estava no projeto... eu só adicionei o meu projeto csharp para fazer o teste.

2024-06-23 20:54 UTC, magnussolidus commented on op-desafios.sln
@ronaldofas Você não precisa enviar o arquivo da solução (este arquivo .sln) para o desafio. Somente o código que está em Program.cs.
Não precisa refazer o commit, mas você precisa tirar este arquivo do git, não deve deletar ele dos seus arquivos locais.

Uma coisa é o arquivo existir no diretório, outra é ele ser rastreado pelo git. Este arquivo não precisa do rastreio do git.

2024-06-24 01:09 UTC, MatMercer requested changes

2024-06-24 01:09 UTC, MatMercer commented on op-desafios.sln
@ronaldofas 

```sh
cd op-desafios
git rm op-desafios.sln
git commit ...
```

Fazendo essa alteração, aprovo a PR!

2024-06-26 13:55 UTC, magnussolidus approved these changes
LGTM!

2024-06-26 17:58 UTC, MatMercer approved these changes
Ótimo trabalho! 🚀

2024-06-26 18:00 UTC, merged