Proposta de Solução do exercício 3 em c sharp
OsProgramadores/op-desafios pull request #1060
Opened 2024-06-27 04:13 UTC by ronaldofas

Segue minha proposta de resolução do exercício 03.

2024-06-27 13:54 UTC, magnussolidus commented
@ronaldofas dá uma conferida na saída do pipeline, ele vai lhe explicar pq não passou.
Assim que tiver passando no pipeline clono sua solução e testo localmente.

2024-06-27 14:37 UTC, ronaldofas commented
Resolvido os problemas da checagem. Tem algum extensão que faça isso automaticamente?

2024-06-29 03:18 UTC, magnussolidus commented
> Resolvido os problemas da checagem. Tem algum extensão que faça isso automaticamente?
Se tem alguma, eu desconheço.

2024-06-29 03:24 UTC, magnussolidus commented
@ronaldofas Se você passasse a usar 1 branch para cada desafio iria facilitar muito a vida de quem for fazer o Review. Por hora tenho que ficar catando suas soluções na sua master, o que não é ideal. 
Lembra no desafio 1 para criar um branch para o que se está trabalhando? Porquê você não está fazendo isso para os desafios?

2024-06-29 03:28 UTC, magnussolidus requested changes

2024-06-29 03:28 UTC, magnussolidus commented on desafio-03/ronaldofas/csharp/palindromos/palindromos.csproj
Não dá para saber qual solução usar. Seu PR não tem instruções de como abrir e executar o código. Como abre?
Pq tem 2 subdiretórios? Pq tás enviando teste na solução?

2024-06-29 03:28 UTC, magnussolidus commented on desafio-03/ronaldofas/csharp/palindromosTest/palindromosTest.csproj
Não dá para saber qual solução usar. Seu PR não tem instruções de como abrir e executar o código. Como abre?
Pq tem 2 subdiretórios? Pq tás enviando teste na solução?

2024-06-30 18:52 UTC, ronaldofas commented on desafio-03/ronaldofas/csharp/palindromosTest/palindromosTest.csproj
Estou usando o padrão TDD para desenvolver as soluções, por isso criei um projeto de testes e um projeto com o resultado. No outro PR me falaram que não precisava arquivo de solução... por isso só criei o projeto e testei. Vou providenciar um README com o processo para executar sem solução.

2024-06-30 19:36 UTC, ronaldofas commented on desafio-03/ronaldofas/csharp/palindromosTest/palindromosTest.csproj
Adicionei o arquivo `ComoExecutar.md` na pasta para explicar como executo aqui na minha máquina o código... trabalho com linux e uso somente o Visual Studio Code e o dotnet para desenvolver por isso executo dessa forma, mas mesmo assim testei numa VM com windows como executar no Visual Studio e coloquei lá também.

2024-06-30 22:15 UTC, magnussolidus commented on desafio-03/ronaldofas/csharp/palindromosTest/palindromosTest.csproj
@ronaldofas não precisa criar arquivos.md com as instruções de como executar o código.
Você tá indo além do que é pedido nos desafios, mas tá fazendo tudo a sua maneira, o que dificulta revisar os PRs. 

Já pensou cada um fazendo o que bem entende para cada desafio?!

**Atenha-se ao que o desafio pede**, qualquer coisa extra pode ficar no seu projeto local, mas não precisa ser enviado para a solução do desafio.

Por favor, siga as orientações para fazer os desafios!

2024-06-30 22:21 UTC, magnussolidus commented
Lista de mudanças necessárias para este desafio:

- [ ] Adicionar descrição coerente ao PR. A única linha que possui não explica nada. Talvez o que você adicionou no arquivo md deveria estar na descrição do PR?
- [x] Remover arquivos de solução (sln) do repositório
- [ ] Remover pasta de testes (Não faz parte do desafio!)

Para os desafios seguintes:

- [ ] Seguir os padrões de Git instruído no desafio 1 (Atenção especial ao item 9 - você não fez isso para os desafios 2 e 3)

2024-06-30 22:26 UTC, magnussolidus commented
PR Fechado. Você pode tentar novamente quando estiver disposto a seguir o que deve ser feito.

Lista de mudanças necessárias para este desafio:

- [ ] Adicionar descrição coerente ao PR. A única linha que possui não explica nada. Talvez o que você adicionou no arquivo md deveria estar na descrição do PR?
- [x] Remover arquivos de solução (sln) do repositório
- [ ] Remover pasta de testes (Não faz parte do desafio!)
- [ ] Seguir os padrões de Git conforme instruído no desafio 1 (Atenção especial ao item 9 - você não fez isso para os desafios 2 e 3)

2024-06-30 22:26 UTC, closed without merging