Desafio 02
OsProgramadores/op-desafios pull request #1061
Opened 2024-06-28 23:40 UTC by Leandro208

2024-06-29 03:32 UTC, magnussolidus requested changes
Confira a saída do pipeline, ela irá lhe ajudar a entender os erros no código.

Também adicione uma descrição no seu PR. No momento desta revisão não há descrição alguma.

2024-06-29 03:32 UTC, magnussolidus commented on desafio-02/leandro208/cpp/primos.cpp
> +    for(int i = 1; i<=11; i++){
O desafio cita:
> Escreva um programa para listar todos os números primos entre 1 e 10000, na linguagem de sua preferência.

Por que você está indo até o número 11 apenas?

2024-07-03 22:38 UTC, Leandro208 commented on desafio-02/leandro208/cpp/primos.cpp
> +    for(int i = 1; i<=11; i++){
digitei errado, irei corrigir

2024-07-03 23:08 UTC, magnussolidus commented
@Leandro208 rodei o pipeline e ele falhou. Dá uma conferida na saída dele para saber o que está errado.
Se for problema de formatação dá uma conferida no nosso linter (pergunte no grupo no telegram se não souber como usá-lo).

2024-07-03 23:25 UTC, Leandro208 commented
@magnussolidus aparentemente era algumas linhas vazias que o pipeline acusou

2024-07-05 00:24 UTC, magnussolidus approved these changes
LGTM!

2024-07-05 00:26 UTC, merged