Desafio03
OsProgramadores/op-desafios pull request #1062
Opened 2024-06-30 23:37 UTC by ronaldofas

Segue minha proposta de resolução do exercício 03.

Como executar

* Visual Studio Code e dotnet

Para executar o projeto com a solução do desafio abra um terminal na pasta principal do repositório ("op-desafios") e execute o seguinte comando:

```
dotnet run --project desafio-03/ronaldofas/csharp/palindromos/palindromos.csproj
```

Para que os comandos acima funcionem corretamente é necessário ter o dotnet instalado em sua máquina.

- Visual Studio

Para executar no Visual Studio basta abrir a pasta pelo Visual Studio e abrir o arquivo `Program.cs` e clicar em executar na barra de atalhos.

2024-07-09 19:07 UTC, magnussolidus requested changes
Sua solução me parece incompleta, visto que ela apenas reproduz os casos de exemplo apresentados no desafio.
Não há como testar outros valores sem realizar alteração do código.

Altere o código de modo a permitir que o usuário possa inserir os valores de piso e teto para o cálculo dos palíndromos.

A exibição dos casos de exemplo é desnecessária.

2024-07-13 15:27 UTC, ronaldofas commented
Olá,

Alterei a entrada do aplicativo para que o usuário seja questionado do ponto inicial  e também o ponto final de avaliação do valores. Foi retirado os padrões de teste propostos no desafio.

Att.

Ronaldo.

2024-07-29 14:48 UTC, ronaldofas commented
Olá, ainda tem alguma coisa a ser melhorada? Pode validar se está tudo ok?

2024-07-30 16:32 UTC, magnussolidus commented
> Olá, ainda tem alguma coisa a ser melhorada? Pode validar se está tudo ok?

Ainda não tive tempo de revisar. Vou tentar conferir hoje quando voltar da minha consulta.

@ronaldofas Esse vai ser o último PR que vou revisar, depois só vou poder voltar a olhar as coisas na segunda quinzena de outubro. Se demorarem a olhar manda uma mensagem lá no grupo do Telegram por favor.

2024-08-04 01:09 UTC, magnussolidus approved these changes
LGTM!

2024-08-04 01:10 UTC, merged