Desafio 02
OsProgramadores/op-desafios pull request #1086
Opened 2024-10-13 05:15 UTC by brenosantos

2024-10-13 08:48 UTC, magnussolidus requested changes
Está com erro de formatação. Deve ter algum espaço em branco ou “tab” sobrando. Confira a formatação por favor e ajuste-a.

2024-10-13 18:47 UTC, magnussolidus reviewed
Me parece OK agora, pelo menos não acusou nada no linter. Vou deixar como comentário assim quem for revisar de fato seu PR não fica agarrado pelo meu pedido de ajustes. :)

2024-10-14 21:33 UTC, Adriana236 approved these changes

2024-10-14 21:33 UTC, Adriana236 approved these changes

2024-10-14 21:41 UTC, magnussolidus commented
@Adriana236 ????

2024-10-18 04:20 UTC, mpinheir commented
@brenosantos adiciona por favor um README para explicar as dependências e como executar a sua solução. Obrigado.

2024-10-19 01:01 UTC, mpinheir commented
@brenosantos você vai dar continuidade ao PR? Se nào for dar, feche por favor o PR. Obrigado!

2024-10-19 01:29 UTC, closed without merging