Desafio 02 - Primos
OsProgramadores/op-desafios pull request #1089
Opened 2024-10-13 18:13 UTC by Vinissokkj

Otimizei o código utilizando o Crivo de Eratosthenes e criei um README.md explicando como executar o código.

2024-10-13 18:49 UTC, magnussolidus requested changes

2024-10-13 18:49 UTC, magnussolidus commented on desafio-02/Vinissokkj/python/README.md
> +1 - Faça o clone ou download do projeto.<br>
Por gentileza, adicione a URL do seu projeto aqui.

2024-10-15 09:34 UTC, magnussolidus commented
Não é para fechar esse PR e abrir um novo só para fazer os ajustes solicitados, não é assim que funciona!

Você envia as correções NO MESMO PR.

2024-10-26 18:54 UTC, marcopaganini commented
Alo @Vinissokkj

Está quase tudo 100%. O único detalhe menor é que o presubmit está falhando porque está faltando um newline no final do seu arquivo (basicamente, a última linha não tem um "enter" no final):

```
Run ./ci/pycheck.sh

======================
Python (v3) code check
======================
* Checking desafio-02/Vinissokkj/python/primos.py
************* Module primos
desafio-02/Vinissokkj/python/primos.py:13:0: C0304: Final newline missing (missing-final-newline)

-----------------------------------
Your code has been rated at 9.17/10
```

Por favor adicione, mande um `git add`, `git commit` e `git push` pra gente poder mergear.

2024-10-26 18:57 UTC, marcopaganini commented
Se voce usa o VSCode, pode evitar esse problema fazendo o seguinte (direto da Internet):

* Open Visual Studio Code and go to File (Code if using a Mac) -> Preferences -> Settings; you should now be viewing a settings page.
* Enter 'insert final newline' in to the search bar
* Select the checkbox under the heading 'Files: Insert Final Newline' in the 'Workspace Settings' and/or 'User Settings' tab(s) as required.
```

2024-11-12 23:55 UTC, closed without merging