@devjunr - Resolução Desafio 2
OsProgramadores/op-desafios pull request #1093
Opened 2024-10-14 01:55 UTC by devJunr

2024-10-14 13:02 UTC, magnussolidus requested changes
Por favor, dê uma conferida nos detalhes da ação.
A estrutura está errada: a validação é case sensitive, `Java` e `java` são coisas distintas para ele.
O correto é java, tudo em minúsculo.

2024-10-14 13:13 UTC, magnussolidus requested changes

2024-10-14 13:13 UTC, magnussolidus commented on desafio-02/devjunr/Java/DesafioNumPrimo.java
> +public class DesafioNumPrimo {
Esta pasta com Java não faz parte da solução. Não é para enviá-la. 
Você deve excluir a pasta Java (com J maiúsculo) e enviar a sua solução na pasta java (com j minúsculo).

2024-10-14 13:15 UTC, magnussolidus commented on desafio-02/devjunr/Java/DesafioNumPrimo.java
> +public class DesafioNumPrimo {
No mínimo, exclua-a do git.

2024-10-14 18:08 UTC, magnussolidus requested changes
A indentação está errada (tem espaços extras). Dá uma conferida na saída do pipeline que você perceberá o problema.

2024-10-19 03:41 UTC, marcopaganini commented
O código continua com [problemas de indentação](https://github.com/OsProgramadores/op-desafios/actions/runs/11339292302/job/31576139244?pr=1093). Tudo com um "-" na frente tem que sair e tudo com um "+" tem que entrar. Voce pode observar que o código é identico, mas está faltando um nível de indentação no seu código.

2024-10-19 08:42 UTC, magnussolidus reviewed
Comentando para não ficar travando um merge.

2024-10-21 01:40 UTC, marcopaganini approved these changes

2024-10-21 01:44 UTC, merged