Desafio 02 por @Donicad
OsProgramadores/op-desafios pull request #1100
Opened 2024-10-16 14:21 UTC by Donicad

Solução para o desafio 02 ajustada, adicionei um arquivo README.md como foi solicitado explicando sobre o código.

2024-10-18 04:25 UTC, mpinheir commented
@Donicad está bonito o README. Que tal usar o crivo de etatostnes para reduzir a quantidade de verficações e aumentar a velocidade da aplicação?

2024-10-18 11:26 UTC, Donicad commented
Bom dia, obrigado pela sugestão, não sabia o que era o crivo de etatostnes, irei pesquisar sobre e criar uma nova solução usando esse método.
O quanto antes atualizo esse PR.

2024-10-19 01:17 UTC, mpinheir requested changes
@Donicad olhe por favor o enunciado do problema. Sua solução só está mostrando primos menores que 1000.

2024-10-22 04:27 UTC, mpinheir commented
@Donicad a especificação do desafio pede para exibir primos menores que 10 mil. Sua solução exibe apenas os menores que 1000. Verifique por favor e ajuste.

2024-10-23 01:19 UTC, mpinheir approved these changes
Parabéns!

2024-10-23 01:19 UTC, merged