Conclusão do Desafio 02
OsProgramadores/op-desafios pull request #1101
Opened 2024-10-17 03:55 UTC by JamesStewart-314

2024-10-18 04:28 UTC, mpinheir commented
@JamesStewart-314 está ficando bacana, Quer dar uma olhada no crivo de eratostenes para tentar reduzir a quantidade de verificações e aumentar a velocidade da Aplicação?

2024-10-19 01:36 UTC, lucasfturos commented on desafio-02/JamesStewart-314/python/desafio02.py
> +
James, remova esse espaço.  O linter ta acusando erro

2024-10-19 01:47 UTC, mpinheir requested changes
@JamesStewart-314 excutei sua soluçào e nada acontece., Tem que instalar algo?
Outra coisa, seria bacana você implementar o crivo ao invés de usar uma lib

2024-10-21 04:03 UTC, mpinheir approved these changes
Parabéns!

2024-10-21 04:03 UTC, merged