Primeiro envio do Desafio 03 por Talita Costa
OsProgramadores/op-desafios pull request #1105
Opened 2024-10-18 16:52 UTC by talita048

## Contatos:
- Github: @talita048 
- Telegram: https://t.me/talita_s_costa

2024-10-19 00:56 UTC, mpinheir requested changes
@talita048 gostei.
Sugiro uma modificação:
Sua solução está permitindo que o usuário digitar um segundo número menor que o primeiro.
Implemente uma verificação para evitar isso e peça para o usuário digitar o número novamente caso isso acontece.

2024-10-19 00:57 UTC, mpinheir commented
@talita048 um outro problema da aplicação.
Eu digitei o primeiro número como um número negativo.
Note o que aconteceu.
Trate isso e evite este problema
Bem-vindo(a) ao detector de números palíndromos!
Um número palíndromo é aquele que permanece igual quando lido de trás para frente.
Insira dois números e vou te informar todos os palíndromos que existem entre eles :D
Digite o primeiro número: -3909123
Digite o segundo número: 10
Traceback (most recent call last):
  File "/home/marcelo/Projects/OsProgramadores-Projetos/op-desafios/desafio-03/talita048/python/desafio03.py", line 11, in <module>
    reverso = int(str(limite_a)[::-1])
              ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '3219093-'

2024-10-19 00:59 UTC, mpinheir commented
@talita048 mais um problema identificado.
A aplicação está permitindo que letras sejam digitadas.
Trate este problema
Bem-vindo(a) ao detector de números palíndromos!
Um número palíndromo é aquele que permanece igual quando lido de trás para frente.
Insira dois números e vou te informar todos os palíndromos que existem entre eles :D
Digite o primeiro número: a
Traceback (most recent call last):
  File "/home/marcelo/Projects/OsProgramadores-Projetos/op-desafios/desafio-03/talita048/python/desafio03.py", line 5, in <module>
    limite_a = int(input("Digite o primeiro número: "))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'a'

2024-10-20 21:29 UTC, talita048 commented
Código revisado!

2024-10-21 00:25 UTC, mpinheir requested changes
@talita048 está quase lá mas precisa de um ajuste.
Note que eu digitei o segundo número menor que o primeiro e você mostrou corretamente o erro mas ao invés de me forçar a corrigir o segundo número você me levou de volta a ter que digitar o primeiro número.
Sugiro pedir para corrigir o segundo número apena
Vide mensagens abaixo e aguardo o Ajuste.
Bem-vindo(a) ao detector de números palíndromos!
Um número palíndromo é aquele que permanece igual quando lido de trás para frente.
Insira dois números e vou te informar todos os palíndromos que existem entre eles :D
Digite o primeiro número: 90909
Digite o segundo número: 3
O primeiro número deve ser menor que o segundo. Tente novamente.
Digite o primeiro número:

2024-10-21 00:25 UTC, mpinheir commented
@talita048 está quase lá mas precisa de um ajuste.
Note que eu digitei o segundo número menor que o primeiro e você mostrou corretamente o erro mas ao invés de me forçar a corrigir o segundo número você me levou de volta a ter que digitar o primeiro número.
Sugiro pedir para corrigir o segundo número apena
Vide mensagens abaixo e aguardo o Ajuste.
Bem-vindo(a) ao detector de números palíndromos!
Um número palíndromo é aquele que permanece igual quando lido de trás para frente.
Insira dois números e vou te informar todos os palíndromos que existem entre eles :D
Digite o primeiro número: 90909
Digite o segundo número: 3
O primeiro número deve ser menor que o segundo. Tente novamente.
Digite o primeiro número:

2024-10-21 01:22 UTC, talita048 commented
Acredito ter resolvido (e com uma mudança muito simples!)
Gostei dessa modificação, aprendi muito com ela.

2024-10-21 03:59 UTC, mpinheir approved these changes
Parabéns!

2024-10-21 03:59 UTC, merged

2024-10-21 13:43 UTC, talita048 commented
Obrigada pela ajuda!