add solution for challenge n° 03 by @imalisoon
OsProgramadores/op-desafios pull request #1107
Opened 2024-10-19 22:27 UTC by imalisoon

2024-10-21 00:37 UTC, mpinheir requested changes
@imalisoon alguns ajustes necessários.
Note as mensagens abaixo.
1-Quando eu digitei o primeiro número como negativo você já deveria ter dado erro ali ao invés de me permitir digitar o segundo número.
2-Quando eu digitei o segundo número menor que o primeiro você me forçou a voltar a digitar o primeiro número. Isso não é necessário pois meu erro é no seguindo número.

Informe o primeiro numero: a
O primeiro e ultimo numero precisam ser interios positivos, nao letras!
Informe o primeiro numero: -30
Informe o ultimo numero: -10
O primeiro e ultimo numero precisam ser POSITIVOS! nao negativos ou ZEROS.
Informe o primeiro numero: 93849238492384923849238492384238423
Informe o ultimo numero: 1
O ultimo numero nao pode ser MENOR que o primeiro numero
Informe o primeiro numero:

2024-10-21 22:52 UTC, imalisoon commented
@mpinheir Pronto! Mudei um pouco a lógica de input e melhorou.

2024-10-22 04:33 UTC, mpinheir requested changes
@imalisoon está quase mas sua solução não está deixando selecionar o valor zero como o valor do primeiro número.

2024-10-22 13:36 UTC, imalisoon commented
@mpinheir Resolvido! Falta de atenção minha.

2024-10-23 01:41 UTC, mpinheir approved these changes
Parabéns!

2024-10-23 01:41 UTC, merged