feat: Conclusão do desafio 03 - @JamesStewart-314
OsProgramadores/op-desafios pull request #1108
Opened 2024-10-22 01:31 UTC by JamesStewart-314

2024-10-22 05:42 UTC, helioloureiro reviewed
Bem complexo o algoritmo.  Só não entendi bem o porquê de pedir números acima de 51.

Fora a complexidade, com lambda e typing hints, só olhando o código, parece que está certo.

2024-10-22 09:21 UTC, helioloureiro commented
Nada contra o código ser complexo.  Não significa que seja ruim.  É que pra olhar pelo telefone fica mais... não tão simples.  Mas é limitação minha aqui.

2024-10-24 05:45 UTC, helioloureiro requested changes
Eu precisei olhar o enunciado de novo.  A implementação não está certa.

Você tem de aceitar inteiros positivos.  Então não existe o limite de começar no 51.

Se entrar com 20, tem de gerar: 1, 2, 3, 4, 5, 6, 7, 8, 9 ,11.

2024-10-24 17:15 UTC, helioloureiro commented
@JamesStewart-314 mil desculpas.  A culpa é toda minha.  Agora eu abri como deveria ter feito antes and o código está bom.  Eu acchava que daria problema a forma que faz mexe com o tty dando um clear no final, mas parece que passou no teste.  Então está bom pra ser adicionado.

2024-10-24 17:15 UTC, helioloureiro reviewed
Aprovado.

2024-10-24 17:15 UTC, helioloureiro reviewed
Aprovado.

2024-10-24 23:56 UTC, rocketguedes commented
Nossa! **extremamente** complexo e difícil de ler, tenho um conhecimento médio em Pyhton e para mim é quase inelegível. Se desviou muito do objetivo, boa parte do código foca em dar uma _boa experiencia_ mas não é isso que entrega.

1. Pela visão de um usuário eu não gostaria que o terminal fosse limpo antes e depois, os números que eu gostaria de descobrir foram limpos do terminal sem o desejo do usuário. Falha no objetivo principal que é mostrar os palíndromos.
2. O _pressione para sair_ e o delay são inconvenientes, a primeira vez que executei achei que tinha travado.
3. Por que limitar os parâmetros de algumas funções a posições e não poder usar keywords?
4. Se era para ter um countdown visível no terminal, não foi visível para mim no Linux

2024-10-25 01:08 UTC, rocketguedes commented
> > Nossa! **extremamente** complexo e difícil de ler, tenho um conhecimento médio em Pyhton e para mim é quase inelegível. Se desviou muito do objetivo, boa parte do código foca em dar uma _boa experiencia_ mas não é isso que entrega.
> > 
> > 1. Pela visão de um usuário eu não gostaria que o terminal fosse limpo antes e depois, os números que eu gostaria de descobrir foram limpos do terminal sem o desejo do usuário. Falha no objetivo principal que é mostrar os palíndromos.
> > 2. O _pressione para sair_ e o delay são inconvenientes, a primeira vez que executei achei que tinha travado.
> > 3. Por que limitar os parâmetros de algumas funções a posições e não poder usar keywords?
> > 4. Se era para ter um countdown visível no terminal, não foi visível para mim no Linux.
> > 5. Sinto fortes influencias de C na escrita, o que dificulta muito a leitura do código.
> > 6. Uso de f string na _docstring_ superior, uso de _back slash_ para preservar aspas simples dentro de aspas duplas, incontáveis formas de dificultar a leitura e manutenção.
> > 7. Entre outras coisas.
> 
> Entendido! Revisei todos os tópicos solicitados:
> 
> • Removi a limpeza do resultado após o término do programa, agora o resultado é persistido no terminal; • O programa agora encerra após exibir o resultado; • Nenhum parâmetro posicional está limitado; • Countdown removido; • Remoção das docstrings e aspas simples prexifadas com backslash.

**WOW!** Mudou da água para o vinho, tanto em usabilidade como em leitura, agora sim, muito bom!
Dá só uma olhada na saída do comando: `pylint solution.py` lá tem algumas pequenas coisas que você pode ajustar.

No topo você pode trocar o uso o `#` para `"""` e.g.:
```python
"""This is the example module.

This module does stuff.
"""
```
Ai o `pylint` para de "reclamar" :D.

2024-10-25 04:19 UTC, mpinheir commented
Está bonita esta discussão. @rocketguedes dá mais uma revisada e me avisa quando ok para aprovar.

2024-10-25 23:32 UTC, rocketguedes requested changes

2024-10-25 23:32 UTC, rocketguedes commented on desafio-03/JamesStewart-314/python/solution.py
> +number_is_palindromic: Callable[[int], bool] = lambda x: (strNumber := str(x)) == strNumber[::-1]
Essa linha pode ser facilmente convertida em uma função nomeada.

O uso de `lambda` e `Callable` não é ideal aqui. O `lambda` geralmente é utilizado como uma função anônima, enquanto nesse caso a função é a atribuída a uma variável nomeada (`number_is_palindromic`). Atribuir uma função `lambda` a uma variável perde o propósito do `lambda` que é ser curto e anônimo. O uso so operador `:=` (`walrus`) pode dificultar a legibilidade desnecessariamente mas é compreensível o uso dela.

Recomendo converter essa linha para uma função nomeada, isso tornará o código menos complexo, melhora a legibilidade e facilita a manutenção.

> [The Zen of Python](https://peps.python.org/pep-0020/#the-zen-of-python)

> Beautiful is better than ugly.
> Explicit is better than implicit.
> Simple is better than complex.
> Complex is better than complicated.
> Flat is better than nested.

2024-10-25 23:32 UTC, rocketguedes commented on desafio-03/JamesStewart-314/python/solution.py
> +            userInput: int = int(input(message if message else ""))
Algumas variáveis como `strNumber`, `userInput`, `palindromicNumbersFound`, `firstNumber`, `secondNumber`, não estão conforme o estilo de nomenclatura `snake_case`

[Function and Variable Names](https://peps.python.org/pep-0008/#function-and-variable-names)

2024-10-26 01:43 UTC, rocketguedes commented
@mpinheir para mim, é OK para aprovar. @JamesStewart-314 ao ajudar a revisar sua PR também aprendi junto! Boa Sorte nos desafios seguintes.

2024-10-26 02:35 UTC, mpinheir approved these changes

2024-10-26 02:35 UTC, merged