@Devjunr - Desafio 03
OsProgramadores/op-desafios pull request #1110
Opened 2024-10-22 13:12 UTC by devJunr

2024-10-22 18:54 UTC, devJunr commented
```
        }
     }
   }
-}
\ No newline at end of file
+}
```

Essa correção não terá o mesmo efeito da forma que já está?

2024-10-23 01:32 UTC, mpinheir requested changes
@devJunr está quase lá mas está aceitando eu digitar letras ou palavras como parâmetros. Precisa tratar isso pois nunca se pode confiar no usuário da tua aplicação
java palindromicos.java A B
Exception in thread "main" java.lang.NumberFormatException: For input string: "A"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at palindromicos.main(palindromicos.java:3)

2024-10-24 01:51 UTC, mpinheir commented
@devJunr Precisa ajustar a mensagem de erro pois números negativos são inteiros também. Neste caso a mensagem de erro precisa dizer que os dois valores precisam ser inteiros positivos.
java palindromicos.java -30
É necessário pelo menos dois valores inteiros como argumento

2024-10-24 02:12 UTC, mpinheir approved these changes
Parabéns!

2024-10-24 02:12 UTC, merged