Solução desafio 03 @Donicad
OsProgramadores/op-desafios pull request #1113
Opened 2024-10-23 18:16 UTC by Donicad

2024-10-24 02:00 UTC, mpinheir requested changes

2024-10-24 02:00 UTC, mpinheir commented on desafio-03/Donicad/python/README.md
> +    try:
Não permita o usuário digitar o segundo número caso o primeiro número seja inválido
python3 palin.py
Digite um numero inicial: -30
Digite um numero final: -40
Erro: Apenas números positivos

2024-10-25 12:57 UTC, Donicad commented on desafio-03/Donicad/python/README.md
> +
Muito obrigado pelos feedbacks, estão me ajudando muito.

2024-10-25 21:57 UTC, imalisoon commented
@Donicad Tá ótimo a solução! Mas, uma sugestão, coloca uma mensagem mais apropriada pra quando o usuário digitar o **segundo** número menor que o *"primeiro**.

2024-10-26 02:38 UTC, mpinheir commented
@Donicad faça por favor e modificação com o @imalisoon pediu. Obrigado.

2024-10-26 02:41 UTC, mpinheir requested changes

2024-10-26 02:41 UTC, mpinheir commented on desafio-03/Donicad/python/README.md
> +            print("Erro: Apenas números podem ser inseridos.")
Esta mensagem não está legal para este caso:
python3 palin.py 1 10000
Digite um numero inicial: -30
Erro: Apenas números podem ser inseridos.

2024-10-26 02:41 UTC, mpinheir commented on desafio-03/Donicad/python/README.md
> +        print("Nenhum palindromo encontrado com esse intervalo.")
Esta mensagem não está boa para esta situação:
python3 palin.py
Digite um numero inicial: 10000
Digite um numero final: 1
Nenhum palindromo encontrado com esse intervalo.


Você precisa tratar a entrada de dados e assegurar que os dados entrados estão corretos e o segundo número não pode ser menor que o primeiro

2024-10-27 18:22 UTC, mpinheir commented
@imalisoon faz mais um review e confirma se good to merge. Obrigado

2024-10-27 20:25 UTC, imalisoon commented
@Donicad @mpinheir Parabéns!! Tudo certo, pronto pro merge.

2024-10-29 04:37 UTC, mpinheir approved these changes
Parabéns!

2024-10-29 04:37 UTC, merged