feat: Resolução do Desafio 6 - @JamesStewart-314
OsProgramadores/op-desafios pull request #1119
Opened 2024-10-26 23:19 UTC by JamesStewart-314

2024-10-27 02:02 UTC, anthonylgf requested changes

2024-10-27 02:02 UTC, anthonylgf commented on desafio-06/JamesStewart-314/python/anagramWords.txt
No readme voce pode explicar como rodar

- Baixe o arquivo de palavras
- Renomeie para o anagramsWords.txt

2024-10-27 02:02 UTC, anthonylgf commented on desafio-06/JamesStewart-314/python/solution.py
> +for anagramTuple in sorted(all_anagrams):
Cara, teu programa não está retornando a saída certa em alguns casos, eu não vi o motivo.

Mas teste com o input `animal`

Ele não retorna as duas saídas em vermelho abaixo
![image](https://github.com/user-attachments/assets/5b62a1d7-17dd-468e-92e9-e69a5f148e8d)

2024-10-27 02:05 UTC, anthonylgf commented
Vi que já abriu vários PR's desse desafio, ao fazer uma mudança, não precisa fechar o PR, faça a adição neste mesmo PR

2024-10-27 17:58 UTC, anthonylgf commented
Cara, vi que consertou algumas coisas, mais ainda tem um erro no teu programa, em alguns casos ele está repetindo a palavra na linha de saída

Teste com esse input `HAAALL`, a saída do teu programa é 
```
A A HALL
A AH ALL
A ALLAH
A ALL HA
AHA ALL
```

Mas a saída correta seria
```
A AH ALL
A ALLAH
A ALL HA
AHA ALL
```

A primeira linha da tua saída está repetindo o `A` duas vezes, não deveria fazer isto.

Outro exemplo de input `AHAH`, a tua saída é
```
A HAH
AH AH
AH HA
HA HA
```
Tem duas linhas que ele repete a mesma palavra mais de uma vez

2024-10-27 18:48 UTC, anthonylgf commented
@JamesStewart-314 sem problemas, falei deste caso só porque na descrição 3 do desafio https://osprogramadores.com/desafios/d06/#o-problema fala que não pode repetir linhas ou palavras

2024-10-28 09:35 UTC, anthonylgf requested changes

2024-10-28 09:35 UTC, anthonylgf commented on desafio-06/JamesStewart-314/python/solution.py
> +    print(*anagramTuple)
Último comentário, acho que é bom deixar esse bloco código nesse formato abaixo:

```python
if __name__ == "__main__":
   # bloco de código que criou executando os passos
```

Só algo cosmético mesmo, para saber onde você está só definindo as funções e a partir de onde começa realmente a execução do algoritmo, do jeito que está agora fica um pouco difícil de achar as vezes

2024-10-30 04:40 UTC, mpinheir commented
@anthonylgf pode revisar?

2024-10-30 09:11 UTC, anthonylgf commented
A tua solução ainda não está exibindo oa valores corretos para alguns casos.

Tentei com o input `VERMELHO LARANJA`, o correto seria gerar uma saída com 5722 linhas. Teu programa está gerando umas 20 linhas a mais

2024-10-30 09:11 UTC, anthonylgf requested changes
Verificar saída com o iput `VERMELHO LARANJA`

2024-10-31 22:26 UTC, anthonylgf commented
@JamesStewart-314 vou dar só uma conferida hoje mais tarde e te dou uma resposta, beleza?

2024-11-04 04:47 UTC, mpinheir commented
@anthonylgf pode dar uma verificada se tudo ok?

2024-11-12 00:30 UTC, mpinheir commented
@JamesStewart-314 sua solução dá erro se eu digito palavras com acento tipo mãe. Trate terros por favor
Oha o erro:
python3 palin3.py mãe
Error: Invalid Characters in the Expression.

2024-11-12 00:31 UTC, mpinheir commented
@JamesStewart-314 seu programa trava com a seguinte palavra. Verifique se está travando ou é meramente tempo de processamento. Eu tenho um Ryzen 5 3600X aqui com 32GB de RAM e não deveria estar demorando para dar resultado.
python3 palin3.py inconstitucionalissimamente

2024-11-12 04:01 UTC, mpinheir commented
@JamesStewart-314 tens razão em ambas. Eu olhei a mensagem de erro ao digitgar mãe e achei que o programa tinha abortado e não é o caso. 
Parabéns por completar o desafio 6.

2024-11-12 04:01 UTC, mpinheir approved these changes

2024-11-12 04:02 UTC, mpinheir commented
@anthonylgf o merge está blocked até vocÊ aprovar pois tinhas pedido reviews.

2024-11-12 04:11 UTC, mpinheir commented
@JamesStewart-314 você não está no https://t.me/osprogramadores?

2024-11-13 00:21 UTC, anthonylgf approved these changes
Aprovado, desculpe a demora, tudo certo!

2024-11-13 00:21 UTC, merged