Desafio-08 por @flafmg.
OsProgramadores/op-desafios pull request #1122
Opened 2024-10-27 22:39 UTC by flafmg

2024-11-05 20:24 UTC, WashingtonARamos commented on desafio-08/flafmg/csharp/FracSimples.cs
> +            string line;
Você pode mover essa declaração para dentro do loop e usar pattern matching para saber quando o objeto não será mais null, assim:

```
try
{
    while (sr.ReadLine() is { } line)
    {
        Console.WriteLine(ProcessFraction(line.Trim()));
    }
}
```

2024-11-05 20:24 UTC, WashingtonARamos commented on desafio-08/flafmg/csharp/FracSimples.cs
> +        var sr = new StreamReader(filePath);
Prefira usar using invés de ter o bloco `finally` no final do código, assim:

`using var sr = new StreamReader(filePath);`

2024-11-05 20:25 UTC, WashingtonARamos requested changes
Revisar comentários, de resto tudo ok.

2024-11-08 16:30 UTC, flafmg commented
correções implementadas, obrigado!

2024-11-10 18:33 UTC, WashingtonARamos commented on desafio-08/flafmg/csharp/FracSimples.cs
> +        catch (Exception ex)
Este bloco é inválido, você não está dando `catch` em nada porque não há um `try`.

2024-11-11 13:10 UTC, flafmg commented on desafio-08/flafmg/csharp/FracSimples.cs
> +        catch (Exception ex)
Resolvi pelo celular

2024-11-13 13:10 UTC, WashingtonARamos approved these changes
lgtm

2024-11-13 13:10 UTC, merged