Minha tentativa de resposta ao desafio 3.
OsProgramadores/op-desafios pull request #1124
Opened 2024-10-29 23:29 UTC by AlexPHorta

Olá, segue minha resposta para o desafio 3.

2024-10-30 09:56 UTC, anthonylgf requested changes

2024-10-30 11:20 UTC, AlexPHorta commented on desafio-03/AlexPHorta/python/desafio03.py
> +    if length > 1:
Oi, Anthony! Só de fazer passar no linter já simplifiquei muito o código. Acho que agora vai!

2024-10-30 20:21 UTC, AlexPHorta commented on desafio-03/AlexPHorta/python/desafio03.py
> +    if length > 1:
Fala, Anthony, tudo ok? Veja se era essa questão do elif. Removi, ficou só o else.

2024-10-31 22:18 UTC, anthonylgf requested changes

2024-10-31 22:18 UTC, anthonylgf commented on desafio-03/AlexPHorta/python/desafio03.py
> +
Acredito que aqui tem muito if aninhado, o teu código anterior estava quase perfeito

Cuidado ao aninhar if's, isto deixa a leitura do código bem ruim
```python
if
   # codigo
else
   # codigo
   if 
      # codigo
   else
      # codigo 
        if
           # codigo
```

Percebe que este padrão é ruim de ler?


Aqui no teu código, o primeiro if, já pode retornar o valore de True, aí ao inves de usar o else, só retira ele e retorna os valores

Tipo
 
```python
     if length == 1:
        return True
      
     head = candidate[0]
     tail = candidate[-1]
     
     if head == tail:
         if length == 2:
             return True
          else:
              return is_palindrome(candidate[1:-1])

    return False
```

Quanto menos ifs ainhados seu código tem, melhor a leitura, o nome desse padrão é o famoso early return: https://www.dio.me/articles/sobre-early-return-ou-o-caminho-das-negativas

2024-10-31 22:18 UTC, anthonylgf commented on desafio-03/AlexPHorta/python/desafio03.py
> +
E esse exemplo que mandei acima, ainda dá para melhorar, usando o ealry return para retirar os ifs aniinhados

2024-11-01 13:15 UTC, AlexPHorta commented
E aí,  Anthony, acho que essa ficou bem enxuta. Veja se roda legal!

2024-11-01 16:27 UTC, mpinheir requested changes
@AlexPHorta or favor altere a forma de executar o desafio para me permitir executar assim: python app inicio fim
Você não deve forçar o usuário a ter que criar uma aplicação para importar seu pacote para rodar as funções que você criou.
Obrigado!

2024-11-03 04:09 UTC, AlexPHorta commented
Olá, Marcelo, fiz com argparse. Veja se ficou bom!

2024-11-04 04:00 UTC, marcopaganini approved these changes

2024-11-05 12:13 UTC, imalisoon commented
@AlexPHorta A saída está correta!

Algumas sugestões...

Você poderia mostrar como executar o programa caso o usuário executasse sem passar os parâmetros.

Melhoria nas mensagens caso o usuário digite *números negativos*, *segundo número* menor que o *primeiro* e caso o usuário passe apenas 1 argumento.

A saída é a mesma para todos esses casos.

2024-11-06 00:13 UTC, AlexPHorta commented
@imalisoon, tudo ok?

Acrescentei diferentes descrições para cada uma das exceções. Agora executar o programa sem argumentos chama a tela de ajuda. Veja se ficou legal!


> @AlexPHorta A saída está correta!
> 
> Algumas sugestões...
> 
> Você poderia mostrar como executar o programa caso o usuário executasse sem passar os parâmetros.
> 
> Melhoria nas mensagens caso o usuário digite _números negativos_, _segundo número_ menor que o _primeiro_ e caso o usuário passe apenas 1 argumento.
> 
> A saída é a mesma para todos esses casos.

2024-11-06 04:06 UTC, mpinheir commented
@imalisoon tem mais alguma coisa que o @AlexPHorta precisa resolver?

2024-11-06 04:16 UTC, mpinheir commented
@AlexPHorta bacana que você mostra instruções sobre como executar mas notei que parte das instruções estào em inglês e parte em Português. Sugiro exibir tudo em Português neste caso.
Vide exemplo abaixo
usage: palin2.py [-h] [-n] [-t] [extremes ...]

Lista todos os números palíndromos existentes entre dois extremos.

positional arguments:
  extremes       Os números inicial e final para a busca.

options:
  -h, --help     show this help message and exit
  -n, --noprint  Somente retorne os resultados.
  -t, --test     Roda os testes.

2024-11-06 13:30 UTC, imalisoon commented
@mpinheir @AlexPHorta Não, Está tudo OK.

2024-11-12 01:36 UTC, AlexPHorta commented
Pronto, a ajuda está em português. Fiz com uma função (que achei no Stack Overflow, claro https://stackoverflow.com/q/22951442). Estava tentando com o Pybabel, mas não consegui.

2024-11-12 04:09 UTC, mpinheir approved these changes

2024-11-12 14:52 UTC, mpinheir approved these changes

2024-11-12 14:53 UTC, mpinheir approved these changes

2024-11-13 05:18 UTC, merged