add challenge 2 by @luanhmilano
OsProgramadores/op-desafios pull request #1139
Opened 2024-11-09 01:24 UTC by luanhmilano

Resolução do Desafio 02 em JavaScript.

2024-11-09 03:24 UTC, marcopaganini requested changes

2024-11-09 03:24 UTC, marcopaganini commented on desafio-02/luanhmilano/javascript/desafio-02.js
> +            contadorDeDivisoes++;
Aqui voce já sabe que o número não é primo, logo por que não sair do loop imediatamente? Com isso, voce pode trocar o contadorDeDivisoes pra um booleano e testar na saida.

2024-11-09 16:16 UTC, luanhmilano commented on desafio-02/luanhmilano/javascript/desafio-02.js
> +            contadorDeDivisoes++;
Alterei a lógica de identificar o primo usando um boolean e quebrando o while, mas fiz um merge das outras modificações de usuários junto com o meu código.

2024-11-12 04:13 UTC, mpinheir commented
@luanhmilano você está no https://t.me/osprogramadores ?

2024-11-12 11:48 UTC, luanhmilano commented
> @luanhmilano você está no https://t.me/osprogramadores ?

Estou sim, vou abrir uma discussão por lá, meu username é "luanducode"

2024-11-16 17:15 UTC, devJunr commented
Cada PR deve conter apenas um desafio. Sua alteração impactou outros 10 desafios

```
Errors:

❌ Found 10 desafios in this PR. Please submit one PR for each:
  - desafio-02/luanhmilano/javascript/
  - desafio-03/AlexPHorta/python/
  - desafio-03/fernandojeff/python/
  - desafio-03/maurilioSo/java/
  - desafio-06/JamesStewart-314/python/
  - desafio-06/maurilioSo/java/
  - desafio-08/flafmg/csharp/
  - desafio-10/imalisoon/python/
  - desafio-11/imalisoon/python/
  - desafio-12/imalisoon/python/
```

2024-12-05 00:01 UTC, closed without merging