Desafio 03 feito em javascript por @joseildoandrade12
OsProgramadores/op-desafios pull request #1157
Opened 2024-11-27 05:00 UTC by joseildoandrade12

2024-11-28 04:02 UTC, mpinheir requested changes
@joseildoandrade12 a solução tem que permitir ao usuário selecionar o intervalo de números a ser analisado pelo programa e não analisar apenas o intervalo entre 1 e 100. Ajusde por favor a sua solução.

2024-11-29 02:12 UTC, mpinheir reviewed
@joseildoandrade12 seu programa não funciona coforme necessário. Antes de mandar o PR teste na sua máquina e assegure que está fazendo o que está fazendo. Seu programa não está pedindo o intervalo de números ao usuário. Por favor não submita PR para review sem isso estar funcionando na sua máquina. Obrigado!

2024-11-29 23:48 UTC, magnussolidus requested changes

2024-11-29 23:48 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +
Seu readme não contém as instruções de como rodar seu programa, muito menos os requisitos necessários.
Adicione essas informações nele, sem isso não consigo testar sua solução.

2024-11-30 00:16 UTC, joseildoandrade12 commented on desafio-03/joseildoandrade12/javascript/README.md
> +
tem algum exemplo de como eu possa fazer essa parte? algum README de inspiração? não sou bom com o readme

2024-11-30 00:20 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +
[Aqui um bom exemplo](https://github.com/OsProgramadores/op-desafios/blob/master/desafio-03/bpires/javascript/readme.md)

2024-11-30 08:49 UTC, magnussolidus requested changes

2024-11-30 08:49 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +
Poxa cara, eu te mandei um bom exemplo e você modificou ele tirando a parte mais importante...

O texto tá igual na parte de teste e execução, só ajustaste o link do git.
**Mas a principal linha tu tirou:**

`Faça um clone do repositório para a máquina local, e rode o arquivo no node, passando os números como argumentos:`

2024-11-30 08:49 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +```bash
Com isso agora fica solto as suas instruções de bash a seguir.

Qual é a versão do Node que vc tá usando? 
Como que faz o processo pra rodar sua solução?

Essas coisas precisam estar no Readme. 

Meu comentário inicial fala dos requisitos e das instruções.
Você botou pela metade os requisitos e menos da metade das instruções...

Trabalhe em melhorar o Readme com as suas próprias palavras.

Como estudo, olhe o [readme do próprio repositório dos desafios](https://github.com/OsProgramadores/op-desafios/).
Compare ele com as instruções que você fez.
Imagine se a mesma abordagem que a sua fosse usada no repositório dos desafios e faça a seguinte pergunta:

Ficou mais fácil?

2024-11-30 21:27 UTC, joseildoandrade12 commented on desafio-03/joseildoandrade12/javascript/README.md
> +```bash
Perdão pelo erro, irei ajustar assim que possível e tentarei deixar de forma mais clara possível de como utilizar. Agradeço por apontar os erros!

2024-12-01 14:03 UTC, magnussolidus requested changes

2024-12-01 14:03 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +$ cd .\op-desafios\
A forma como você coloca os comandos é dependente da plataforma. 
Ao executar este comando em um terminal linux ele não vai entrar no diretório `op-desafios`.
Onde você está desenvolvendo, você precisa colocar esse `.` antes da barra para acessar o subdiretório?

2024-12-01 14:03 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +$ node .\desafio-03\joseildoandrade12\javascript script.js
Aqui você instrui a executar algo que não está disponível no repositório base antes de ser _mergeado_.
Também tem a mesma questão do `.` antes de passar o caminho. 
De brinde tem o detalhe do path estar quebrado, já que tem um espaço em branco em `javascript script`.
Você não executou essas instruções que colocaste aqui, né?

2024-12-01 14:03 UTC, magnussolidus commented on desafio-03/joseildoandrade12/javascript/README.md
> +Após iniciar o arquivo irá aparecer as seguintes perguntas:
A partir deste ponto não é possível validar, visto que as instruções atuais não permitiram executar o seu código.

2024-12-01 21:11 UTC, closed without merging