feat: Conclusão do desafio 10 - @JamesStewart-314
OsProgramadores/op-desafios pull request #1158
Opened 2024-11-28 23:37 UTC by JamesStewart-314

2024-11-29 02:04 UTC, mpinheir commented
@helioloureiro pode revisar por favor? Obrigado!

2024-12-02 16:26 UTC, helioloureiro requested changes
Algumas partes podem melhorar.

2024-12-02 16:26 UTC, helioloureiro commented on desafio-10/JamesStewart-314/python/solution.py
> +                if self._current_state in self._turing_rules and current_symbol in\
Acho que é possíve melhorar aqui também com princípios de clean code.

Subistituir `self._current_state in self._turing_rules` por `check_state(self._current_state, self._turing_rules)` por exemplo.  E criar um simples:

```python
def check_state(state, rules):
    return state in rules
```

idem pra símbolo.

```python
def check_symbol(symbol, state, rules):
    return symbol in rules[state]
```

Isso ima melhorar muito a legibilidade.

2024-12-02 16:26 UTC, helioloureiro commented on desafio-10/JamesStewart-314/python/solution.py
> +        datafile_obj.close()
Não precisa.

2024-12-03 13:50 UTC, helioloureiro commented on desafio-10/JamesStewart-314/python/solution.py
> +            self._restore_initial_state()
Tem razão.  Não percebi esse detalhe.  Acho que o nome do método atrapalha nesse sentido.  Um `_reset(  )` seria mais claro.

2024-12-03 13:52 UTC, helioloureiro approved these changes
Aprovado.

2024-12-03 13:52 UTC, helioloureiro commented on desafio-10/JamesStewart-314/python/solution.py
> +                    symbols_map = self._turing_rules[self._current_state]
Ficou bem mais legível assim.  Muito bom.

2024-12-04 05:51 UTC, mpinheir approved these changes

2024-12-04 05:51 UTC, merged