Desafio 12 por @flafmg.
OsProgramadores/op-desafios pull request #1159
Opened 2024-11-30 02:17 UTC by flafmg

2024-11-30 18:47 UTC, magnussolidus reviewed
Assim que eu puder parar para executar o código continuo com o review. Por hora tem alguns comentários.

2024-11-30 18:47 UTC, magnussolidus commented on desafio-12/flafmg/csharp/README.MD
> +   cd op-desafios/desafio-12/flafmg/csharp
Não faltou passar o branch certo aqui?

2024-11-30 18:47 UTC, magnussolidus commented on desafio-12/flafmg/csharp/program.cs
> +        if (args.Length < 1)
Se aqui vc espera que sempre tenha 1 argumento, se `args != 1`. O seu if já está invertido, o que mudaria é só o contexto depois. 
Sai `args > 1`, entra `args == 1`.

2024-11-30 18:47 UTC, magnussolidus commented on desafio-12/flafmg/csharp/program.cs
> +        var lines = File.ReadAllLines(fileName);
Essa semana alertei no trabalho para esse mesmo cara aqui. 
Olha só o tanto de exceções que ele pode trigar e você não está tratando nenhuma: 
https://learn.microsoft.com/en-us/dotnet/api/system.io.file.readalllines?view=net-8.0

Seu if de validação do arquivo trata parte do problema, mas se sair do caminho onde tudo dar certo o que vai acontecer com a execução do seu programa?

2024-11-30 18:47 UTC, magnussolidus commented on desafio-12/flafmg/csharp/program.cs
> +    private static (bool, int) IsPowerOfTwo(BigInteger number)
Poderia ter criado um **struct** ou um **record** para esse cara aqui ao invés da tupla `< bool, int>`, como você fez em outras soluções (mas criaste classes).
Não afeta muito o resultado.

2024-11-30 18:48 UTC, magnussolidus requested changes
Tem que se requested changes para tratar o File.ReadAllLines. Deixei link pra doc dele nos comentários.

2024-11-30 18:53 UTC, magnussolidus commented on desafio-12/flafmg/csharp/program.cs
> +        var fileName = args[0];
Isso aqui é importante como profissional, não para o desafio ok?

Não se utiliza input direto do usuário assim sem vc tratar antes. 
Motivo? Segurança. Você sempre tem que limpar e tratar entrada de dados antes de repassar, caso contrário, seu código fica exposto a injeções de comandos entre outras coisas.

Esse aqui é só para você aprender sobre, caso não saiba. **Não precisa fazer esse ajuste no desafio.**

2024-11-30 21:45 UTC, flafmg commented on desafio-12/flafmg/csharp/program.cs
> +    private static (bool, int) IsPowerOfTwo(BigInteger number)
Achei mais pratico por serem so duas variaveis, mas posso fazer um record ou struct sem problemas tambem :D

2024-11-30 22:01 UTC, flafmg commented on desafio-12/flafmg/csharp/program.cs
> +        var fileName = args[0];
Perdão não entendi muito bem, como poderia ocorrer uma injeção de comando nesse caso e como eu posso evitar?

2024-12-01 12:57 UTC, magnussolidus commented on desafio-12/flafmg/csharp/program.cs
> +    private static (bool, int) IsPowerOfTwo(BigInteger number)
Para desafios isolados, isso não afeta muito. Em um projeto, afetaria. Há de se manter uma constância, um padrão em como as coisas são abordadas.

2024-12-01 14:17 UTC, magnussolidus requested changes
As instruções atuais impossibilitam qualquer validação da solução.
O _Readme_ precisa ser ajustado e os comentários só devem ser marcados como resolvidos **somente quando o problema for realmente resolvido.**
Na dúvida, deixe quem abriu o comentário marcá-lo como resolvido.

2024-12-01 14:17 UTC, magnussolidus commented on desafio-12/flafmg/csharp/README.MD
> +   cd op-desafios/desafio-12/flafmg/csharp
@flafmg Não marque como resolvido problemas que você não resolveu!

```
➜  flafmg cd op-desafios/desafio-12/flafmg/csharp
cd: arquivo ou diretório inexistente: op-desafios/desafio-12/flafmg/csharp
```

2024-12-01 14:20 UTC, magnussolidus commented on desafio-12/flafmg/csharp/program.cs
> +        var fileName = args[0];
Apenas para registro, a explicação foi fornecida no grupo do telegram.

2024-12-01 14:59 UTC, flafmg commented
@magnussolidus perdão, na hora de dar o git add acabei dando so no program.cs e esqueci de adicionar o readme.md

2024-12-01 15:07 UTC, flafmg commented on desafio-12/flafmg/csharp/README.MD
> +   cd op-desafios/desafio-12/flafmg/csharp
Peço desculpar, desatenção minha no git add, e mesmo se eu tivesse adicionado ainda estária errado vi agora, creio ter corrijido já!

2024-12-01 21:10 UTC, magnussolidus commented
Devido ao desprezo deste usuário para com o meu tempo, não revisarei mais nenhum PR do mesmo.

2024-12-01 21:10 UTC, closed without merging

2024-12-01 22:25 UTC, flafmg commented
Perdão, em nenhum momento quis agir com desprezo pelo senhor, pelo contrário, respeito o senhor de verdade como alguém com mais conhecimento do que eu. Sei que cometi erros, mas ainda estou aprendendo, faz parte do processo. Acredito que o senhor também faltou com respeito comigo e com meu colega no grupo. Não queremos causar divergências, não estamos aqui pra isso, estamos aqui para aprender com pessoas mais experiences
Só quero deixar essa mensagem aqui para mostrar meu ponto de vista também, já que no grupo o senhor agiu com certa rigidez conosco e com certo destrato(Não sei se essa palavra esta correta), eu não gosto de acabar causando mal estar, desculpas mais uma vez, tentarei melhorar meus erros e me tornar um programador e pessoa melhor, por favor não interprete essa mensagém como agressiva ou algo do tipo, é dificil passar tom por mensagém então não quero que acabe entendendo errado!

2024-12-02 15:58 UTC, flafmg commented
Não houve desprezo em nenhum momento com o senhor ou seu tempo, peço desculpas se causei algum problema