feat: Conclusão do Desafio 11 - @JamesStewart-314
OsProgramadores/op-desafios pull request #1162
Opened 2024-12-04 21:52 UTC by JamesStewart-314

2024-12-09 05:20 UTC, mpinheir commented
@helioloureiro pode revisar?

2024-12-11 09:26 UTC, helioloureiro requested changes
Ele não passa no exemplo do exercício.

2024-12-11 09:26 UTC, helioloureiro commented on desafio-11/JamesStewart-314/python/solution.py
> +        raise Exception(f"Error: Could open file \'{file_path}\'.") from error
Muito bom.

2024-12-11 09:26 UTC, helioloureiro commented on desafio-11/JamesStewart-314/python/solution.py
> +
Eu não entendi muito bem o algoritmo e não sei bem como passou na validação.  Eu rodei com os 20 decimais do exemplo, e o resultado foi diferente do esperado:

```console
❯ cat pi-1M.txt 
14159265358979323846

❯ python3 solution.py
59265358979323
```

E no exemplo:

![image](https://github.com/user-attachments/assets/878923ba-f17b-4ea5-8851-4e1588a37062)

2024-12-11 09:29 UTC, helioloureiro commented on desafio-11/JamesStewart-314/python/solution.py
> +
@mpinheir acho que tem algum bug na validação.  Esse código aqui não está gerando a sequência certa.

2024-12-12 12:17 UTC, helioloureiro commented on desafio-11/JamesStewart-314/python/solution.py
> +
Ah... eu que comi bola então.  Foi mal.  De resto está ok.  Aprovado.

2024-12-12 12:17 UTC, helioloureiro approved these changes
Aprovado!

2024-12-12 14:37 UTC, mpinheir approved these changes

2024-12-12 14:37 UTC, merged