solução do desafio 05
OsProgramadores/op-desafios pull request #370
Opened 2020-08-01 19:17 UTC by AnaPaulaMazi

Ola,
Estou enviando o desafio 05. 
Desde já agradeço

2020-08-01 19:21 UTC, TravisBuddy commented
Hey @AnaPaulaMazi,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;OsProgramadores&#x2F;op-desafios&#x2F;builds&#x2F;714066955">View build log</a>

###### TravisBuddy Request Identifier: 2d34b560-d42c-11ea-9b7b-6b7bbdba586d

2020-08-02 05:15 UTC, TravisBuddy commented
Hey @AnaPaulaMazi,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;OsProgramadores&#x2F;op-desafios&#x2F;builds&#x2F;714066955">View build log</a>

###### TravisBuddy Request Identifier: 1c092d40-d47f-11ea-ac5f-7b8ff6f8abea

2020-08-02 22:25 UTC, marcopaganini commented
Obrigado @AnaPaulaMazi. Voce confirmou se o resultado bate com os valores esperados quando voce usa os arquivos indicados na página do desafio?

2020-08-04 23:14 UTC, AnaPaulaMazi commented
Marco, fiz os testes, ele processa certo, mais no console os dados aparecem incompletos. Como existem muitos funcionários com mesmo sobrenome, o console mostra apenas o last_name_max.
Agora se inverter a instanciação dos objetos  na classe main() linhas 35 a 39...
			Analises analise = new Analises(funcionariosList, areasList);
			analise.salariosSobrenome();
			analise.salarioGlobal();
			analise.salariosAreas();
			analise.quantidadeFuncionarioArea();
dai aparece certinho no console.... (mais fora da ordem das perguntas do desafio)
tentei usar thread e parallelStream()....mais não consegui arrumar. Será que você pode me dar alguma dica, ou indicar algum material que eu possa consultar?

2020-08-10 01:12 UTC, BernardinoCampos commented
Ana Paula, favor incluir detalhadamente procedimento para compilar e executar, lembrando que ele irá enviar o nome do arquivo para testar como parâmetro que tem que ser o último, caso vc precise que passe algum outro

2020-08-12 19:57 UTC, AnaPaulaMazi commented
Ola Bernardino,
Inclui o procedimento e fiz uma reorganização do programa. 
Aguardo seu retorno e possível solicitação de novas modificações.
Até mais.

2020-08-13 16:32 UTC, BernardinoCampos commented
O nome do arquivo deve ser esperado como parâmetro, e mesmo digitando o nome do arquivo:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/stream/JsonReader
	at desafio05.ClasseMain.main(ClasseMain.java:28)
Caused by: java.lang.ClassNotFoundException: com.google.gson.stream.JsonReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

2020-08-13 16:35 UTC, AnaPaulaMazi commented
Ok..vou fazer as correções.

2020-08-14 21:38 UTC, AnaPaulaMazi commented
Seguem novas alterações

2020-08-27 19:44 UTC, BernardinoCampos requested changes
Ana,

  Por favor troque o ponto decimal para ponto, está em virgula e assim o MD5 não bate, e troca o 

least_employess para least_employees

2020-09-11 17:11 UTC, AnaPaulaMazi commented
Bernardino,
Peço desculpas por demorar, mais meu note deu problema, tive que mandar arrumar e demorou. Só ficou pronto ontem.
Então se puder, eu faço a alteração na sequencia.

2020-09-14 19:39 UTC, BernardinoCampos requested changes
Ana,

   Rodando os 25M estourou memória!

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1002)
        at com.google.gson.stream.JsonReader.nextName(JsonReader.java:788)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at ClasseMain.main(ClasseMain.java:36)

2020-09-30 04:07 UTC, closed without merging