Solução do Desafio 5 em Scala
OsProgramadores/op-desafios pull request #381
Opened 2020-08-03 16:49 UTC by lrlucena

2020-08-03 23:39 UTC, marcopaganini commented
Verificou os resultados?

2020-08-05 04:27 UTC, lrlucena commented
> Verificou os resultados?

Eu testei com a entrada do exemplo e o resultado foi o esperado. Testei também com as entradas de 10K e 30M mas os MD5 não coincidiram. Você pode verificar o resultado para a entrada de 10K?

https://gist.github.com/lrlucena/09d5b7ba068d75eb35e8071ddfbc7c26

2020-08-10 21:22 UTC, lrlucena commented
### Instalação de Scala 2.12+

A maneira mais simples de instalar Scala no Linux é usando o SDKMAN (https://sdkman.io)

```
$ curl -s "https://get.sdkman.io" | bash
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
```

### Execução

```
$ scalac desafio05.scala -d desafio05.jar
$ scala desafio05.jar Funcionarios-10K.json | sort
```

2020-08-11 16:03 UTC, BernardinoCampos commented
Lucena,

      Quando eu rodo na mão funciona, quando eu rodo ele dentro da "Jaula" dá erro, eu devo precisar passar algo no enviroment, hoje estou mandando 'LANG'=>'pt_BR.UTF-8' que é suficiente para o Java, vc tem idéia do que seja?

     E quando eu rodo ele na mão, ele está retornando os números com , e preciso deles com . padrão, tem algum enviroment para trocar isto ou está posto na mão? 

Bernardino Campos

2020-08-11 17:28 UTC, lrlucena commented
Ola @BernardinoCampos 

Executando o comando 'locale -a' eu obtenho:

```
C
C.UTF-8
POSIX
en_US.utf8
```

Eu testei colocando `export lang="pt_BR.UTF-8"` e deu erro. Com `export lang="en_US.utf8"` e `export lang="C.UTF-8"` funciona corretamente.

2020-08-27 18:59 UTC, BernardinoCampos requested changes
Lucena,

    Foi sem problemas até o arquivo de 1M, ai não foi, o erro é de arredondamento.

diff OK NAOOK 
1,2c1,2
< area_avg|Área 1|49961.41
< area_avg|Área 2|50037.65
---
> area_avg|Área 1|49961.39
> area_avg|Área 2|50037.75
7c7
< global_avg|49967.27
---
> global_avg|49967.26
4926,4927c4926,4927
< least_employees|Área 2|76924
< most_employees|Área 1|923076
---
> least_employees|Área 2|76923
> most_employees|Área 1|923075

2020-08-27 20:43 UTC, lrlucena commented
Eu vou alterar o tipo da variavel que guarda a soma de `double` para `BigDecimal` para ver se resolve.

2020-08-28 17:22 UTC, lrlucena commented
@BernardinoCampos 
Havia um erro no parser Json que ignorava os últimos elementos da sequência de funcionários. Você poderia testar novamente?

2020-08-28 18:48 UTC, BernardinoCampos approved these changes
Aprovado, todos os Hash bateram, resultado já está na página junto com o gráfico comparativo de velocidades!

2020-08-28 18:48 UTC, merged