Solução do desafio 05 em Javascript
OsProgramadores/op-desafios pull request #420
Opened 2020-08-21 00:26 UTC by brunosana

2020-08-27 15:39 UTC, BernardinoCampos commented
Bruno, 

    Para eu poder rodar ele e ele poder constar ele tem que rodar em console mode, ou seja nodeJs, e eu vou passar como parâmetro o nome do arquivo

   E teste para todos os arquivos lá disponíveis inclusive o de 30M de registros, que é ai que a coisa pega!

2020-08-27 15:43 UTC, brunosana commented
A linha 99 recebe o arquivo passado pela linha de comando.

2020-08-28 12:14 UTC, BernardinoCampos requested changes
Bruno,

   Houve o seguinte erro:

$ node Exec/Js-BrunoSana.js Arquivos/Funcionarios-10K.json 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './Arquivos/Funcionarios-10K.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/OsProgramadores/Exec/Js-BrunoSana.js:99:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

    Como vc pode ver o arquivo está lá disponível

$ ls -la Arquivos/Funcionarios-10K.json 
-rw-r--r--. 1 programadores programadores 821252 Nov  9  2017 Arquivos/Funcionarios-10K.json

FYI

$ node --version
v10.22.0

$ npm --version
6.14.6

2020-08-28 13:28 UTC, brunosana commented
Irei reabrir o PR. Pois os commits que estou inserindo na branch não estão sendo feitos neste PR.

2020-08-28 13:29 UTC, closed without merging