Desafio05
OsProgramadores/op-desafios pull request #428
Opened 2020-08-28 13:31 UTC by brunosana

Reabrindo o PR. Pois os commits que estavam sendo feitos nessa branch não estavam entrando no PR anterior.

Foi encontrado um erro no código ao passar o arquivo por linha de comando:

```
$ node Exec/Js-BrunoSana.js Arquivos/Funcionarios-10K.json
internal/modules/cjs/loader.js:638
throw err;
```

Isso aconteceu pois usei o "require" para importar direto da linha de comando, embora aqui no PC tenha funcionado, pesquisando um pouco vi que não era o correto.

Alterei o código usando o package "fs" para abrir o arquivo, funcionou aqui no PC espero que aí também.

2020-08-28 14:06 UTC, BernardinoCampos requested changes
Bruno,

    Foi um pouco mais adiante, mas, voltou a dar erro, vc está testando com os arquivos que estão no site? Os MD5 bateram? Estou usando o de 10K

$ node Exec/Js-BrunoSana.js Arquivos/Funcionarios-10K.json 
global_min | Aakash Brino | 1.96
global_max | Aahron Galvan | 99993.96
global_avg | 49648.19
area_min | Área 1 | Aakash Brino | 1.96
area_max | Área 1 | Aahron Galvan | 99993.96
area_avg | Área 1 | 49731.80
area_min | Área 2 | Aakash Agosti | 137.82
area_max | Área 2 | Aakash Bracci | 99884.08
area_avg | Área 2 | 48646.04
/OsProgramadores/Exec/Js-BrunoSana.js:68
        console.log(`area_min | ${e.nome} | ${f.nome} ${f.sobrenome} | ${f.salario.toFixed(2)}`);
                                                ^

TypeError: Cannot read property 'nome' of undefined
    at global_min.forEach.f (/OsProgramadores/Exec/Js-BrunoSana.js:68:49)
    at Array.forEach (<anonymous>)
    at funcionarios.areas.forEach.e (/OsProgramadores/Exec/Js-BrunoSana.js:67:44)
    at Array.forEach (<anonymous>)
    at fs.readFile (/OsProgramadores/Exec/Js-BrunoSana.js:62:24)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

2020-08-28 14:11 UTC, brunosana commented
Farei uma análise mais completa

2020-08-28 18:58 UTC, BernardinoCampos requested changes
Bruno,

Vc testou o MD5? Os resultados não batem, a formatação não está igual.

na linha do readFile tire o ./

Vou te mandar só o início de um resultado válido

area_avg|Área 1|49731.80
area_avg|Área 2|48646.04
area_max|Área 1|Aahron Galvan|99993.96
area_max|Área 2|Aakash Bracci|99884.08
area_min|Área 1|Aakash Brino|1.96
area_min|Área 2|Aakash Agosti|137.82
global_avg|49648.19
global_max|Aahron Galvan|99993.96
global_min|Aakash Brino|1.96
last_name_max||Aakash |45715.03
last_name_max|Abaine|Aakash Abaine|57682.36
last_name_max|Abate|Aahron Abate|64106.68
last_name_max|Abato|Aahron Abato|89912.17
last_name_max|Abaurre|Aakash Abaurre|34797.24
last_name_max|Abbe|Aahron Abbe|86401.26
last_name_max|Abbott|Aahron Abbott|89506.48
last_name_max|Abbruzzese|Aahron Abbruzzese|52940.09
last_name_max|Abbud|Aalam Abbud|88787.85
last_name_max|Abecassis|Aalam Abecassis|92644.95
last_name_max|Abela|Aahron Abela|59473.81
last_name_max|Abella|Aahron Abella|98234.52
last_name_max|Aboudib|Aahron Aboudib|23612.90
last_name_max|Abramo|Aalam Abramo|83579.84
last_name_max|Abreu|Aakash Abreu|96256.40
last_name_max|Abruzzese|Aakash Abruzzese|59484.30
last_name_max|Abruzzo|Aahron Abruzzo|70110.84
last_name_max|Accardi|Aahron Accardi|71737.44

2020-09-11 17:50 UTC, brunosana commented
PR Obsoleto

2020-09-11 17:50 UTC, closed without merging