Melhoria da solução do desafio 05 em C
OsProgramadores/op-desafios pull request #431
Opened 2020-08-29 00:43 UTC by cbcalves

2020-09-14 19:48 UTC, BernardinoCampos requested changes
Deu erro no hash, faltaram coisas

/var/tmp/OK:last_name_max|Bernardo|Aahron Bernardo|85907.24
/var/tmp/OK:last_name_max|De Bernardo|Aakash De Bernardo|61068.50
/var/tmp/OK:last_name_max|Di Bernardo|Aakash Di Bernardo|71154.02
/var/tmp/NAOOK:last_name_max|De Bernardo|Aakash De Bernardo|61068.50
/var/tmp/NAOOK:last_name_max|Di Bernardo|Aakash Di Bernardo|71154.02

2020-09-15 00:07 UTC, cbcalves commented
> Deu erro no hash, faltaram coisas
> 
> /var/tmp/OK:last_name_max|Bernardo|Aahron Bernardo|85907.24
> /var/tmp/OK:last_name_max|De Bernardo|Aakash De Bernardo|61068.50
> /var/tmp/OK:last_name_max|Di Bernardo|Aakash Di Bernardo|71154.02
> /var/tmp/NAOOK:last_name_max|De Bernardo|Aakash De Bernardo|61068.50
> /var/tmp/NAOOK:last_name_max|Di Bernardo|Aakash Di Bernardo|71154.02

Corrigido, tinha uma função em posição errada incluíndo o sobrenome antes de inicializar as variáveis, o que levava alguma thread a pegar um sobrenome e tentar modificar enquanto as variáveis eram inicializadas, ou seja colisão de dados.

2020-10-30 05:46 UTC, marcopaganini commented
Bernie, esse PR está ativo ainda. O Carlos disse que corrigou o problema. Voce tentou rodar novamente?

2020-11-06 14:49 UTC, BernardinoCampos approved these changes

2020-11-06 14:49 UTC, merged