Elismar desafios
OsProgramadores/op-desafios pull request #472
Opened 2020-10-13 15:02 UTC by Elismar13

Olá! Aqui vai algumas contribuições para o repositório de soluções.

Desafio 02 em python;
Desafio 03 em C;

2020-10-14 01:19 UTC, mpinheir requested changes
Um PR para cada solução para cada desafio.
Reveja as mensagens de erro do Travis. 
Obrigado.

2020-10-14 16:49 UTC, Elismar13 commented
Vou fechar essa branch então e vou criar mais duas, uma para cada desafio, pode ser?

2020-10-14 18:44 UTC, marcopaganini commented
Sim, funciona. Voce deve ter recebido um email do github diretamente,
dizendo existir erros no PR (nós testamos automaticamente se alguem tenta
enviar mais de um desafio por PR). Tem como confirmar que você realmente
recebeu esse email? (se não recebeu, pode ter algo errado nos nossos testes)

On Wed, Oct 14, 2020 at 9:50 AM Elismar Silva <notifications@github.com>
wrote:

> Vou fechar essa branch então e vou criar mais duas, uma para cada desafio,
> pode ser?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OsProgramadores/op-desafios/pull/472#issuecomment-708527618>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYUYBA4LTLNUTBLLFT3WF3SKXJENANCNFSM4SPBS2HA>
> .
>

2020-10-16 11:59 UTC, Elismar13 commented
Não recebi nada no email, @marcopaganini , apenas as notificações dos comentários de vocês. 

Separei os desafios, mas mesmo assim o teste está reclamando de error de indentation, sendo que minha solução funciona normal aqui. No fim das contas, desisti e vou fechar esta PR. Valeu!

2020-10-16 11:59 UTC, closed without merging