Added solution of the challenge 4 in Python
OsProgramadores/op-desafios pull request #511
Opened 2020-12-28 03:44 UTC by jeffteixeira

2020-12-28 18:14 UTC, mpinheir approved these changes
O programa trava e nada mostra. Verifique se faltou algo.

2020-12-28 18:15 UTC, mpinheir requested changes
O programa trava e nada faz.
Verifique por favor se faltou algo.

2020-12-28 18:20 UTC, jeffteixeira commented
Imagino que seja por não ter uma mensagem no input. Fiz pensando que a entrada de dados seria igual ao que é mostrado na página do desafio. Cada linha com 8 números seprados por espaço.

2020-12-28 18:21 UTC, jeffteixeira commented
Vou colocar uma mensagem no input

2020-12-28 19:20 UTC, mpinheir requested changes
Continua pendurando e não mostrando nada.
Testa na sua máquina primeiro e se assegure que está funcionando antes de enviar novos pushs para atualizar o pR

2020-12-29 01:40 UTC, mpinheir requested changes
A solução implementada está dando erro se o usuário digita valores diferentes de números na entrada de dados ou se digita um valor maior do que o máximo número que pode ser armazenado pelo tipo de dado sendo utilizado na entrada de dados.

2021-01-02 21:29 UTC, mpinheir requested changes
Eu gostei muito das melhorias implemendas mas o programa em geral está pouco amistoso do ponto de vista do usuário final.
Vão aqui algumas sugestões:
1-Comece exibindo explicações para o usuário para explicar o que deve ser a entrada de dados e as limintações da mesma.
2-Exiba algum tipo de instrução (antes de entrar no looping de entrada de dados) e mostre as peças que equivalem aos numeros 1, 2, 3, etc. ex: 1 = Peão, etc
Espero que isso ajude a melhorar o programa.

2021-01-02 21:31 UTC, jeffteixeira commented
ok, obrigado pelo comentário

2021-01-06 05:49 UTC, mpinheir commented
Gostei muito das melhorias.
Algumas sugestões:
1-Crie uma tela com instruções antes de começar a pedir a entrada de dados
2-Dê ao usuário a oportunida de interromper a entrada de dados digitando a letra Q (quit)
3-Para que me fazer digitar um monte de ZEROS depois que eu já usei todas as peças possiveis? Preencha o resto das posições no tabulheiro com ZERO quando o usuário já tiver selecionado todas as peças possíveis.

2021-01-17 18:40 UTC, mpinheir approved these changes
Aprovado! Agora é partir para a versão com interface gráfica.

2021-01-17 20:03 UTC, merged