Desafio-04 Inserção inicial da solução em ALGO68 @jjmg-eng
OsProgramadores/op-desafios pull request #527
Opened 2021-01-09 16:30 UTC by jjmg-eng

2021-01-09 20:41 UTC, mpinheir approved these changes
Sugestão: Tratar erro caso o usuário digite um arquivo que não existe pois senão o programa aborta.

2021-01-10 02:26 UTC, jjmg-eng commented
> Sugestão: Tratar erro caso o usuário digite um arquivo que não existe pois senão o programa aborta.

< O programa foi modificado para exibir uma mensagem de falha caso seja fornecido um nome de arquivo inexistente e terminar a execução sem erro.

2021-01-10 06:11 UTC, mpinheir requested changes
Continua dando erro quando eu seleciono um arquivo que não existe.
Teste e verifique por favor.

2021-01-10 11:18 UTC, jjmg-eng commented
> Continua dando erro quando eu seleciono um arquivo que não existe.
> Teste e verifique por favor.

< Por favor, confirme se no seu caso acontece um "crash" do programa ou se a mensagem de erro é a que eu programei para aparecer quando um nome de arquivo inexistente é fornecido.

2021-01-10 14:14 UTC, jjmg-eng commented
> > Continua dando erro quando eu seleciono um arquivo que não existe.
> > Teste e verifique por favor.
> 
> < Por favor, confirme se no seu caso acontece um "crash" do programa ou se a mensagem de erro é a que eu programei para aparecer quando um nome de arquivo inexistente é fornecido.

Veja abaixo os resultados da execução no meu computador:

jjmg@jjmg-Lenovo-ideapad-320-14IKB:~/ALGOL68$ ./xadrez.a68 
Nome do arquivo:ex1.txt

Peão  :         +4 peça(s)
Bispo :         +0 peça(s)
Cavalo:         +0 peça(s)
Torre :         +0 peça(s)
Raínha:         +0 peça(s)
Rei   :         +0 peça(s)
jjmg@jjmg-Lenovo-ideapad-320-14IKB:~/ALGOL68$ a68g xadrez.a68 ex2.txt 
a68g: error: multiple source file names at option "ex2.txt".
jjmg@jjmg-Lenovo-ideapad-320-14IKB:~/ALGOL68$ a68g --script xadrez.a68 ex2.txt 

Peão  :        +16 peça(s)
Bispo :         +4 peça(s)
Cavalo:         +4 peça(s)
Torre :         +4 peça(s)
Raínha:         +2 peça(s)
Rei   :         +2 peça(s)
jjmg@jjmg-Lenovo-ideapad-320-14IKB:~/ALGOL68$ ./xadrez.a68 ex1.txt

Peão  :         +4 peça(s)
Bispo :         +0 peça(s)
Cavalo:         +0 peça(s)
Torre :         +0 peça(s)
Raínha:         +0 peça(s)
Rei   :         +0 peça(s)
jjmg@jjmg-Lenovo-ideapad-320-14IKB:~/ALGOL68$ ./xadrez.a68 ex1
Erro na abertura do arquivo
jjmg@jjmg-Lenovo-ideapad-320-14IKB:~/ALGOL68$ ./xadrez.a68 
Nome do arquivo:ex1
Erro na abertura do arquivo

2021-01-27 04:27 UTC, mpinheir commented
O programa submetido continua dando erro se eu entro com o nome de um arquivo qualquer. Estou estando o código no Ubuntu 20.04.

2021-04-27 03:18 UTC, marcopaganini commented
PR fechado por falta de atividade.

2021-04-27 03:18 UTC, closed without merging