Solução do desafio 2 em C usando teste de divisão
OsProgramadores/op-desafios pull request #532
Opened 2021-01-12 18:09 UTC by weslleymberg

2021-01-13 02:12 UTC, mpinheir requested changes
Seu programa está imprimindo números que não são primos.

ex:

9977
9979
9983
9985
9989
9991
9995
9997

2021-01-13 12:36 UTC, weslleymberg commented
Vou conferir. 👍🏼

2021-01-13 14:00 UTC, weslleymberg commented
Resolvido! Exatos 1229 numeros primos sendo gerados agora.

Fonte da quantidade de primos: https://primes.utm.edu/howmany.html (Table 1)

2021-01-16 02:44 UTC, mpinheir approved these changes
Approved.

2021-01-16 02:44 UTC, merged