Solução do desafio 2 em Elixir
OsProgramadores/op-desafios pull request #537
Opened 2021-02-07 22:37 UTC by TeijiW

2021-02-13 18:08 UTC, mpinheir requested changes
Jovem, a solução está imprimindo 1 como primo e 1 não é primo.
Adicione também instruções para nós podermos entender como executar a sua solução.
Eu coloquei apenas a rotina principal no Repl.it e funcionou.
Seria importante também você explicar como os testes estão sendo executados.

2021-02-22 00:46 UTC, mpinheir commented
@TeijiW Você vai atualizar a solução ou abandonar?

2021-02-22 00:49 UTC, TeijiW commented
Vou atualizar, solicito que me dê até amanhã para isso.

2021-02-22 12:49 UTC, TeijiW commented
@mpinheir Para executar a rotina principal, utilize o comando `mix run -e "PrimeNumbers.main"`
Quanto aos testes, eu não havia criado nenhum antes, mas adicionei agora.
Basicamente é um teste com o resultado "estático", não tenho em mente outra maneira de testar esse desafio.
Caso tenha alguma ideia, pode sugerir.

2021-03-07 17:14 UTC, TeijiW commented
@mpinheir Alguma dúvida/problema ao realizar testes no meu desafio?

2021-03-07 18:26 UTC, mpinheir commented
@TeijiW Você resolveu o problema com relação a exibir 1 como número primos? Testou e está fucionando?

2021-03-07 18:28 UTC, TeijiW commented
@mpinheir O problema já foi resolvido e está funcionando.

2021-03-07 18:29 UTC, mpinheir commented
@TeijiW ok. Vou testar.

2021-03-07 18:33 UTC, mpinheir approved these changes

2021-03-07 18:36 UTC, merged