Alcione Ferreira
OsProgramadores/op-desafios pull request #550
Opened 2021-03-12 13:33 UTC by ksombrah

Desafio Completo

2021-04-09 17:53 UTC, BernardinoCampos requested changes
Hash não bate, imprimiu várias linhas em branco na tela.

2021-04-10 00:02 UTC, ksombrah commented
> 
> 
> Hash não bate, imprimiu várias linhas em branco na tela.
> 
> Rodou para os arquivos que existem disponíveis? 10K, 100K, 1M, 10M e 30M???

Vou refazer os testes, mas a princípio tinha processado pelo menos com 1M sem problemas

2021-04-10 01:15 UTC, mpinheir commented
@ksombrah o hash bateu?

2021-04-11 18:10 UTC, BernardinoCampos commented
Alcione,

	Já deu erro em 10K, vc está colocando linhas em branco junto com o resultado, logo não tem como o Hash bater, acerta isto e depois faz o:

      <SEU PROGRAMA> <ARQUIVOS> | sort | md5sum ( Caso seja linux) e confere o resultado com a lista.

Bernardino Campos 


> Em 10/04/2021, à(s) 01:02, Sombra ***@***.***> escreveu:
> 
> 
> Hash não bate, imprimiu várias linhas em branco na tela.
> 
> Rodou para os arquivos que existem disponíveis? 10K, 100K, 1M, 10M e 30M???
> 
> Vou refazer os testes, mas a princípio tinha processado pelo menos com 1M sem problemas
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/OsProgramadores/op-desafios/pull/550#issuecomment-817034279>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABPWFKBSDYKXZK2FWOPX57LTH6IRJANCNFSM4ZCJPJ6A>.
>

2021-04-27 03:19 UTC, marcopaganini commented
PR fechado por falta de atividade.

2021-04-27 03:19 UTC, closed without merging