desafio3
OsProgramadores/op-desafios pull request #585
Opened 2021-05-09 14:00 UTC by vieirajunior-90

2021-05-10 02:00 UTC, mpinheir requested changes
O programa funciona mas eu gostaria que você fizesse uma mudança:
Permita ao usuário digitar o número inicial  e o número final da série de números a ser avaliada.
Reveja o texto do desafio no site.

2021-05-13 23:00 UTC, vieirajunior-90 commented
Acredito que agora o código seja aceito, estava acusando espaços e tabs em várias linhas, removi todos.

2021-05-13 23:46 UTC, marcopaganini approved these changes

2021-05-13 23:47 UTC, merged

2021-05-13 23:47 UTC, marcopaganini commented
:+1: