desafio 02 feito em csharp.
OsProgramadores/op-desafios pull request #594
Opened 2021-05-20 01:02 UTC by jezielsilva

2021-05-20 22:04 UTC, WashingtonARamos requested changes
@jezielsilva você incluiu alguns arquivos binários nos seus commits, remova-os antes do pull request. Você só precisa incluir o arquivo de projeto (*.csproj) e de classes - *.cs, no seu caso Program.cs.

2021-05-21 01:30 UTC, marcopaganini commented
Por favor, não feche o PR e abra outro. Use o mesmo PR. Basta usar git push
com as modificações e ele atualiza.

On Thu, May 20, 2021 at 6:16 PM jezielsilva ***@***.***>
wrote:

> Closed #594 <https://github.com/OsProgramadores/op-desafios/pull/594>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OsProgramadores/op-desafios/pull/594#event-4776694115>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYUYBDJSXIHAEVKTJHBU7LTOWX53ANCNFSM45FZJNYA>
> .
>

2021-05-22 20:31 UTC, WashingtonARamos requested changes
@jezielsilva seu commit ainda possui arquivos binários e arquivos desnecessários. Você pode remove-los do git usando `git rm [nome do arquivo]`. Lembre-se que só é necessário o arquivo de projeto (\*.csproj) e arquivos de código-fonte (\*.cs).

2021-05-25 01:48 UTC, WashingtonARamos requested changes
@jezielsilva remova os comentários no seu arquivo \*.csproj (das linhas 46 -> 53), eles estão conflitando com as checagens pré-envio.

2021-06-02 16:06 UTC, WashingtonARamos approved these changes

2021-06-02 17:03 UTC, merged

2021-06-02 17:04 UTC, WashingtonARamos commented
Aprovado e mergeado. Obrigado pela contribuição @jezielsilva! :)