Resolução do desafio 02 com Python3.
OsProgramadores/op-desafios pull request #597
Opened 2021-06-02 03:13 UTC by paullomarttins

2021-06-02 05:54 UTC, anthonylgf commented on desafio-02/paullomarttins/python/desafio-02.py
> +Desafio 02, listando números primos de 1 até 10000!
Sugiro remover o `!` ao final da linha, pois esse símbolo na matemática representa o [fatorial](https://pt.wikipedia.org/wiki/Fatorial). Quem lê rápido pode achar que seu programa imprime os primos de 1 até 10000 fatorial(e este número é imenso)

2021-06-02 05:59 UTC, anthonylgf commented on desafio-02/paullomarttins/python/desafio-02.py
> +    for valor in range(2, num):
Este bloco de `for` funciona perfeitamente, mas sugiro depois dar uma lida [nas duas primeiras linhas desta seção do artigo de números primos na Wikpedia](https://pt.wikipedia.org/wiki/N%C3%BAmero_primo#Os_%C3%A1tomos_da_aritm%C3%A9tica) e tentar aplicar uma otimização para que este loop não precise percorrer **todos** os números entre 2 e o número que quer testar subtraido de 1

2021-06-02 06:00 UTC, anthonylgf reviewed
- Parabéns por fazer o desafio, é um passo muito bom! O `linter` do python está acusando alguns erros, sugiro que dê uma olhada e corrija, se precisar de ajuda, peça no grupo.

- Deixei duas sugestões para o seu programa, elas não são obrigatórias de serem feitas para o seu programa ser aceito, já que ele funciona, mas servem para aprendizado, se precisar de ajuda, pode nos contatar no Telegram

2021-06-02 21:44 UTC, anthonylgf requested changes
Parabéns por aplicar as correções sugeridas, para se ter uma ideia segue os tempos de execução médio das duas versões dos programas que criou, quando o seu desafio for aprovado, vou te enviar como fiz este benchmark em python para você aprender também:
```
Primeira versao do desafio feita
4.844710881996434s
Segunda versao do desafio feita
0.13127399800578132s
```

Uma evolução de performance tremenda, espero que tenha ficado algum aprendizado, contudo, ainda existem alguns detalhes que precisam serem corrigidos para o teu código ficar completo. Não desista, tá quase lá, deixei dois comentários!

Além disto, veja o nosso ambiente de testes na página `Actions` do Github para ver se o testes para o teu PR estão passando. Você consegue ver o link no próprio PR, se precisar de ajuda, só chamar a gente no grupo

2021-06-02 21:44 UTC, anthonylgf commented on desafio-02/paullomarttins/python/desafio-02.py
> +    if num == 2 or num == 2:
Acredito que este `if`está incorreto, acho que foi algum erro de digitação. 

Além disso, o teu programa não está printando o `3`, acredito que consertando este if conserte este erro

2021-06-02 21:44 UTC, anthonylgf commented on desafio-02/paullomarttins/python/desafio-02.py
> +        print(valor)
Quando se cria um script em python, o ideal, é colocar a parte do código a ser executada(no seu caso as linhas 27, 28 e 29) dentro de um bloco neste formato:
```python
if __name__ == "__main__":
    # inserir as três linhas marcadas
```

[Aqui segue um link](http://devfuria.com.br/python/entenda-__name__-__main__/) do porquê fazermos isto. Qualquer dúvida, só perguntar!

2021-06-03 14:29 UTC, anthonylgf approved these changes
Por mim o programa está ok agora!

@marcopaganini @mpinheir algum de vocês podem dar autorização para este PR rodar no Github Actions?

@paullomarttins assim que o programa executar no Github Actions, basta apenas corrigir os erros que aparecerem e esperar pelo aprovação final e o merge de algum dos mantenedores do projeto!

2021-06-04 01:21 UTC, marcopaganini commented
Rodou e acusou uns problemas menores.

2021-06-07 16:54 UTC, anthonylgf commented
@paullomarttins Faltam algumas pequenas correções a serem feitas, que foram acusadas pelo linter no Github Actions, para você finalizar o desafio? Precisa de alguma ajuda?

Se conseguir, já tire isto da frente, porque não são coisas complexas, para assim poder já partir para outros desafios. Lembre-se também que caso o seu PR fique muito tempo parado, ele pode ser fechado por inatividade.

2021-06-10 04:08 UTC, anthonylgf commented
@marcopaganini o @paullomarttins fez as correções de erro do linter, rodei aqui manualmente e no pylint não apareceu nenhum erro, poderia colocar o Github Actions para rodar novamente, só para confirmar que não tem nenhum erro pendente e já mergear o desafio, se tudo estiver passando e não tiver mais nenhuma consideração a fazer sobre o código

2021-06-10 05:43 UTC, marcopaganini approved these changes

2021-06-10 05:43 UTC, merged

2021-06-10 05:45 UTC, marcopaganini commented
Obrigado @paullomarttins pela contribuição e @anthonylgf pelo excelente trabalho revisando o código.