Adicionar check para codigos em Java - WIP
OsProgramadores/op-desafios pull request #599
Opened 2021-06-21 01:27 UTC by anthonylgf

2021-06-21 01:56 UTC, anthonylgf commented
Este PR ainda está em progresso, o que falta:
- Adicionar no README do projeto as descrições sobre como a formatação de código funciona, quais patterns são utilizados e as versões do Java suportadas
- Adicionar um script que faz a formatação dos códigos em Java de acordo com os padrões utilizados, para ser utilizado pelos desenvolvedores no ambiente local

Irei finalizar estas duas partes amanhã

2021-06-22 02:29 UTC, anthonylgf commented
@marcopaganini Finalizei a implementação do script para checar a formatação do código feito em Java durante o PR.

[Neste commit](https://github.com/OsProgramadores/op-desafios/pull/599/commits/80a893c8ddcaa71b81f98dd3ec31371e4424c6bc) fiz um teste simulando o caso em que o usuário manda um arquivo fora dos padrões aceitos.

Pode verificar e me dar o teu feedback quando for possível?

2021-06-22 03:14 UTC, marcopaganini requested changes

2021-06-22 03:14 UTC, marcopaganini commented on README.md
> +1. O código deve ser feito utilizando o [estilo de desenvolvimento do Google](https://google.github.io/styleguide/javaguide.html).
s/feito/escrito ou talvez formatado?

2021-06-22 03:14 UTC, marcopaganini commented on README.md
> +1. Pull Requests contendo código em Java serão automaticamente verificados pela biblioteca indicada. Ao submeter um PR, observe a tela do PR e verifique se a integração falhou. Em caso de erro, cliqu
Acho uma boa idéia sempre reforçar o fato de que não é necessário fechar o PR e abrir outro, pois o povo tem uma tendência forte a fazer isso e torna reviews impossíveis.

2021-06-22 03:14 UTC, marcopaganini commented on ci/javacheck.sh
> +java -jar ${CACHE_DIR}/google-java-format-"${FORMATTER_VERSION}"-all-deps.jar --set-exit-if-changed ${FILES[@]}
Ele sempre roda o teste ou só quando existirem fontes em java? Idealmente só quando existirem (poupa tempo, mas talvez não muito nesse caso).

2021-06-22 03:14 UTC, marcopaganini commented on .gitignore
> +*.jar
Faltou um \n no final do arquivo (eu tenho que transferir o presubmit do op-website-hugo pra cá pra pegar esses problemas.

2021-06-22 03:15 UTC, marcopaganini commented
Review feita!

On Mon, Jun 21, 2021 at 7:30 PM Anthony Louis ***@***.***>
wrote:

> @marcopaganini <https://github.com/marcopaganini> Finalizei a
> implementação do script para checar a formatação do código feito em Java
> durante o PR.
>
> Neste commit
> <https://github.com/OsProgramadores/op-desafios/pull/599/commits/80a893c8ddcaa71b81f98dd3ec31371e4424c6bc>
> fiz um teste simulando o caso em que o usuário manda um arquivo fora dos
> padrões aceitos.
>
> Pode verificar e me dar o teu feedback quando for possível?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OsProgramadores/op-desafios/pull/599#issuecomment-865475592>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYUYBDWYTI32HXEJOYW6G3TT7YSZANCNFSM47AT635Q>
> .
>

2021-06-22 17:44 UTC, anthonylgf commented on .gitignore
> +*.jar
Correção aplicada!

2021-06-22 17:44 UTC, anthonylgf commented on README.md
> +1. Pull Requests contendo código em Java serão automaticamente verificados pela biblioteca indicada. Ao submeter um PR, observe a tela do PR e verifique se a integração falhou. Em caso de erro, cliqu
Correção aplicada!

2021-06-22 17:47 UTC, anthonylgf commented on README.md
> +1. O código deve ser feito utilizando o [estilo de desenvolvimento do Google](https://google.github.io/styleguide/javaguide.html).
Correção aplicada, troquei para **formatado**.

2021-06-22 18:09 UTC, anthonylgf commented on ci/javacheck.sh
> +java -jar ${CACHE_DIR}/google-java-format-"${FORMATTER_VERSION}"-all-deps.jar --set-exit-if-changed ${FILES[@]}
Ele estava aplicando para todos os arquivos modificados.

Utilizei como base o exemplo do `pycheck` e modifiquei para ser aplicado somente nos arquivos Java

2021-06-22 18:12 UTC, anthonylgf commented
Apliquei as mudanças sugeridas, vou fazer dois commits de testes agora, para testar se a actions continua funcionando após as modificações serem aplicadas

2021-06-22 19:29 UTC, anthonylgf commented
@marcopaganini apliquei as correções pedidas.
- Agora o script só está executando quando tiver modificações em arquivos Java.
- Apliquei as outras duas correções que pediu.

2021-06-23 22:54 UTC, marcopaganini approved these changes

2021-06-23 22:55 UTC, merged

2021-06-23 22:55 UTC, marcopaganini commented
Obrigado Anthony!