Adiciona desafio 2 feito em R
OsProgramadores/op-desafios pull request #603
Opened 2021-06-28 20:22 UTC by viniciusbeckerdesouza

2021-07-11 23:48 UTC, mpinheir requested changes
O programa está listando 1 como primo e 1 por definição não é primo.
Ajuste por favor e mande o push para atualizar o PR.
Note que NÃO é preciso fechar o PR.

2021-07-13 03:03 UTC, mpinheir requested changes
Por favor, não mande vários desafios em um único PR.
Atualize este aqui para conter apenas o desafio 2 e mande outro, separado, com sua solução para o desafio 3.
Obrigado!

2021-07-14 03:54 UTC, mpinheir submitted a review, later dismissed
Você submeteu dois arquivos. Submeta apenas uma solução.
Obrigado!

2021-07-31 21:31 UTC, marcopaganini commented
Fechado por inatividade.

2021-07-31 21:32 UTC, marcopaganini approved these changes

2021-07-31 21:36 UTC, merged