Desafio3
OsProgramadores/op-desafios pull request #605
Opened 2021-07-02 02:05 UTC by jezielsilva

Desafio 03 feito tentando corrigir o erro feito em uma nova branch.

2021-07-02 02:13 UTC, anthonylgf requested changes
@jezielsilva se clicar em `files changed` aqui no Github, vai ver que o PR ainda contém arquivos de dois desafios.

Neste PR, de forma simples, o que precisa fazer é, remover os arquivos do desafio2, fazer o commit e dar push que o PR vai atualizar

2021-07-02 02:14 UTC, anthonylgf commented
Acho que o commit que fez o revert foi o que tinha adicionado o desafio 3, o que precisa remover são os commits do desafio 2.

2021-07-02 02:35 UTC, jezielsilva commented
Uma dúvida: quando você diz remover os arquivos do desafio 02, é na minha máquina?
Eu teria que apagar os arquivos no meu computador do desafio 2, excluir os commits que são do desafio 02, fazer um commit novo para atualizar e dar push. Seria isso?

2021-07-02 02:50 UTC, anthonylgf commented
@jezielsilva Não precisa pedir desculpa, acho que eu que não fui claro.

Não precisa excluir os commmits do desafio. Na sua máquina, dentro desta branch deste PR, vai apagar os arquivos do desafio 2 que fez. Fazer um commit com a exclusão destes arquivos e depois fazer o push, agora está claro?

2021-07-06 01:12 UTC, jezielsilva commented
Eu exclui os arquivos na minha máquina no branch, fiz o commit, dei o push, porém os 2 arquivos ainda estão indo juntos. Se eu excluir eles dois pelo github mesmo, é errado?

2021-07-06 01:44 UTC, anthonylgf commented
@jezielsilva se funcionar e excluir o arquivo do PR, acho que não tem problema algum.

2021-07-07 03:00 UTC, anthonylgf commented
@WashingtonARamos, como não tenho muita familiaridade com códigos em C#, pode dar uma revisada no código que ele fez?

2021-07-08 01:11 UTC, WashingtonARamos commented
@jezielsilva sua implementação não passa pelo exemplo 2 do desafio:
`Exemplo 2: Dado o numero inicial 3000 e número final 3010, o resultado seria: 3003.`
Por favor corrija.

2021-07-09 02:33 UTC, jezielsilva commented
Eu consegui fazer o código da forma correta dessa vez, mas subiram 4 arquivos quando só haviam dois na pasta. Não estou conseguindo excluir eles por aqui. Via código eu consigo?

2021-07-10 01:17 UTC, WashingtonARamos commented
@jezielsilva sua implementação está incorreta. Lembre-se: 
`Palíndromos são frases ou palavras que podem ser lidas, indiferentemente, da esquerda para a direita, conforme o sentido habitual da leitura, ou da direita para a esquerda, sem que haja mudança da sua significação`
No nosso caso, números. Números como 121, 3003, 2112 ou 498894 são palíndromos, pois tanto da esquerda pra direita quanto da direita para a esquerda a leitura é idêntica. Sua implementação está retornando números que não são palíndromos, como 319, 418 ou 495. Corrija a implementação e remova os arquivos inutilizados do commit. Recomendo também aperfeiçoar a estratégia, pois o número máximo atual de sua implementação é 100000, quando o desafio pede um bem maior que isto.

2021-07-31 21:21 UTC, marcopaganini commented
Fechando como abandonado.

2021-07-31 21:21 UTC, closed without merging