Solução em Python do Desafio 02
OsProgramadores/op-desafios pull request #610
Opened 2021-07-12 22:04 UTC by vieirajunior-90

2021-07-12 22:23 UTC, vieirajunior-90 commented
Retirei todas as linhas brancas que estava impedindo de passar, porém na chamada da função recursiva acusa um erro este erro de linha branca, espaço ou tabs. Alguém pode me ajudar ?

2021-07-13 03:06 UTC, mpinheir requested changes
Continua falhando o pre-bubmit check.
Verifique os espaços no final de cada linha e remova.

2021-07-13 13:40 UTC, vieirajunior-90 commented
> Continua falhando o pre-bubmit check.
> Verifique os espaços no final de cada linha e remova.

Marcelo, acho que vou refazer o programa e depois reposto a solução. Como estou aprendendo recursividade, resolvi aplicar nesse programa, mas acaba tornando-se um programa ineficiente por ter muitas chamadas, não entendo direito ainda, mas acredito que isso consuma muita memória. Vou tentar uma outra maneira.

2021-07-14 03:55 UTC, mpinheir commented
@vieirajunior-90 Ok!

2021-07-14 20:07 UTC, vieirajunior-90 commented
@mpinheir Marcelo, consegui dessa vez. Agora vou partir para outro desafio. Valeu !

2021-07-17 00:43 UTC, mpinheir approved these changes

2021-07-17 00:43 UTC, merged