Solução do em Python do Desafio 04
OsProgramadores/op-desafios pull request #613
Opened 2021-07-14 21:59 UTC by vieirajunior-90

2021-07-19 23:31 UTC, anthonylgf requested changes

2021-07-19 23:31 UTC, anthonylgf commented on desafio-04/vieirajunior-90/python/xadrez.py
> +def exemplo_1():
Quem deve preencher o tabuleiro é o usuário no momento que estiver executando o seu programa, dê uma olhada nas condições na descrição do desafio https://osprogramadores.com/desafios/d04/#condi%C3%A7%C3%B5es

2021-07-19 23:31 UTC, anthonylgf commented on desafio-04/vieirajunior-90/python/xadrez.py
> +            bispo += 1 if valor == 2 else 0
Se olhar a descrição do desafio, não é permitido a utilização de `if-else` para a resolução

2021-07-19 23:35 UTC, vieirajunior-90 commented on desafio-04/vieirajunior-90/python/xadrez.py
> +            bispo += 1 if valor == 2 else 0
Fazer o usuário digitar, eu consigo alterar, porém não sei como fazer sem if-else, eu resolvi esse desafio em C com operadores ternários, vou ter que estudar mais nesse para conseguir em python.

2021-07-19 23:41 UTC, anthonylgf commented on desafio-04/vieirajunior-90/python/xadrez.py
> +            bispo += 1 if valor == 2 else 0
Levantei uma discussão com os outros membros do grupo sobre permitir utilizar ou não operadores ternários, mas acho legal achar uma forma diferente de fazer o desafio sem utilizá-los, porque eles se comportam de forma semelhante ao `if-else`, mas com outra notação apenas

2021-07-20 00:15 UTC, anthonylgf commented on desafio-04/vieirajunior-90/python/xadrez.py
> +def exemplo_1():
@vieirajunior-90 na descrição do desafio está escrito que o tabuleiro pode ser definido no próprio código. Dessa forma, pode desconsiderar este comentário acima que fiz, me perdoe pela desatenção.

2021-07-20 00:16 UTC, anthonylgf commented on desafio-04/vieirajunior-90/python/xadrez.py
> +            bispo += 1 if valor == 2 else 0
@vieirajunior-90 atualizei a descrição do desafio no site https://osprogramadores.com/desafios/d04/ para deixar claro que não pode utilizar operadores ternários https://osprogramadores.com/desafios/d04/

2021-07-20 00:31 UTC, vieirajunior-90 commented on desafio-04/vieirajunior-90/python/xadrez.py
> +def exemplo_1():
Tá bom

2021-07-20 00:34 UTC, vieirajunior-90 commented on desafio-04/vieirajunior-90/python/xadrez.py
> +            bispo += 1 if valor == 2 else 0
Sem problemas, fui revisar os métodos de lista agora há pouco e vi um que pode funcionar. Amanhã vou refazer o código e comitar novamente. A solução estava na minha cara, mas a falta de prática faz isso, esquecimento de coisas simples.

2021-07-20 18:09 UTC, anthonylgf approved these changes
Show de bola! Agora está correto, vou aprovar aqui!

2021-07-20 18:10 UTC, merged

2021-07-20 18:14 UTC, anthonylgf commented
@vieirajunior-90 Aprovei e mergei o teu código, porque está funcionando corretamente. Mas umas dicas para melhorá-lo no futuro:
- Extrair a parte que recebe o tabuleiro e faz o processo de contar as peças em um método a parte para evitar a repetição de código
- Ler o input do usuário, para ele poder definir o tabuleiro no momento de executar o código

2021-07-20 18:28 UTC, vieirajunior-90 commented
> @vieirajunior-90 Aprovei e mergei o teu código, porque está funcionando corretamente. Mas umas dicas para melhorá-lo no futuro:
> 
> * Extrair a parte que recebe o tabuleiro e faz o processo de contar as peças em um método a parte para evitar a repetição de código
> * Ler o input do usuário, para ele poder definir o tabuleiro no momento de executar o código

Obrigado! Eu ainda cometo muito esse erro de repetição de código, vou tentar melhorar com certeza.