Devd04
OsProgramadores/op-desafios pull request #618
Opened 2021-07-19 03:55 UTC by theoantolin

2021-07-19 23:58 UTC, anthonylgf requested changes

2021-07-19 23:58 UTC, anthonylgf commented on desafio-04/theoantolin/c/xadrez.c
> +};
Reveja a descrição do desafio no site: https://osprogramadores.com/desafios/d04/#condi%C3%A7%C3%B5es

O usuário deve inserir como está o tabuleiro no momento que está executando o código.

2021-07-19 23:58 UTC, anthonylgf commented on desafio-04/theoantolin/c/xadrez.c
> +		rei = matriz[i][j] == 6 ? ((rei) + 1) : rei;
Na descrição do desafio, ele pede para não utilizar estruturas condicionais. O operador ternário é um `if-else` por debaixo dos panos com uma notação diferente.

Tente resolver de uma maneira diferente, se precisar de ajuda, só perguntar no grupo

2021-07-20 00:13 UTC, anthonylgf commented on desafio-04/theoantolin/c/xadrez.c
> +};
Me perdoe pelo erro, na descrição está escrito que pode ser definido pelo próprio código, então pode desconsiderar este comentário acima que fiz

2021-07-21 23:20 UTC, theoantolin commented on desafio-04/theoantolin/c/xadrez.c
> +		rei = matriz[i][j] == 6 ? ((rei) + 1) : rei;
Tudo bem. Realmente o operador ternário é uma outra forma de utilizar estrutura condicional no código, bem observado.

Vou resolver de outra maneira. Qualquer coisa pergunto no grupo.

2021-07-23 01:41 UTC, closed without merging

2021-07-23 01:42 UTC, theoantolin commented
Solução em JavaScript.