Desafio 02
OsProgramadores/op-desafios pull request #619
Opened 2021-07-21 21:45 UTC by lucassilvagc

Inserindo Desafio 02 em Java.

2021-07-21 22:38 UTC, anthonylgf requested changes
O código está funcionando corretamente, mas sugiro aplicar somente este detalhe que mostrei para permitir que outras pessoas possam testar o teu código quando lerem.

2021-07-21 22:38 UTC, anthonylgf commented on desafio-02/lucassilvagc/java/Desafio2.java
> +package com.company;
Seria legal adicionar um comentário mostrando como compilar e executar o teu código, para caso alguém queria testar.

Os steps que executei na minha máquina foram os seguintes:
```shell
$ javac -d . Desafio2.java
$ java com.company.Desafio2
```

2021-07-22 00:21 UTC, lucassilvagc commented on desafio-02/lucassilvagc/java/Desafio2.java
> +package com.company;
Anthony, resolvido.

Obrigado pelo feedback!

-LS

2021-07-22 01:38 UTC, anthonylgf approved these changes
Parabéns, o código está correto e funcionando corretamente, parabéns pela solução, continue contribuindo com os outros desafios!

2021-07-22 01:39 UTC, merged