Desafio 5 em C++ - @luizfelmach
OsProgramadores/op-desafios pull request #710
Opened 2022-01-28 01:24 UTC by luizfelmach

2022-01-31 15:15 UTC, BernardinoCampos requested changes
Para 50K o md5 não bateu, a diferença é arredondamento

diff resultado*
4c4
< area_max|Área 2|Aamena D’Aversa|99945.4
---
> area_max|Área 2|Aamena D’Aversa|99945.40

2022-02-03 12:58 UTC, luizfelmach commented
Realizei as alterações no arquivo. Realmente não estava batendo o md5 do arquivo de 50K. Agora a saída está correta.

2022-02-04 02:44 UTC, mpinheir commented
@BernardinoCampos pode testar por favor?

2022-02-06 00:14 UTC, BernardinoCampos requested changes
Não rodou os 12M, aguardando alterações!

2022-02-09 20:12 UTC, closed without merging