Added solution to desafio-03
OsProgramadores/op-desafios pull request #728
Opened 2022-02-24 03:52 UTC by DanielRosa74

2022-02-24 23:43 UTC, mpinheir reviewed
Por favor inclua um README para exclicar como o progreama funciona e como deve ser testado.
Trate o input para assegurar que o usuário não crie problemas.Veja resultado abaixo:
abacate
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at PalindromicNumbers.main(PalindromicNumbers.java:7)

2022-02-25 02:11 UTC, DanielRosa74 commented
Creio que agora esteja resolvido, Marcelo! Abraço.

2022-02-25 04:11 UTC, mpinheir reviewed
Deu erro de compilação.
Tem que import algo mais?
PalindromicNumbers.java:26: error: cannot find symbol
    } catch (InputFormatException e) {
             ^
  symbol:   class InputFormatException
  location: class PalindromicNumbers
1 error

2022-02-25 10:17 UTC, DanielRosa74 commented
Sim, não havia importado a Exception.
E não aceitou simplesmente adicionar a linha, mas agora, com a alteração, passou.
Obrigado pelo alerta.

2022-02-28 04:42 UTC, WashingtonARamos requested changes

2022-02-28 04:42 UTC, WashingtonARamos commented on desafio-03/DanielRosa74/java/PalindromicNumbers.java
> +    } catch (InputFormatException e) {
@DanielRosa74 seu código ainda não compila. Talvez invés de `InputFormatException` você esteja tentando dar catch em um [`InputMismatchException`](https://docs.oracle.com/javase/7/docs/api/java/util/InputMismatchException.html)?

2022-02-28 04:42 UTC, WashingtonARamos commented on desafio-03/DanielRosa74/java/PalindromicNumbers.java
> +      for (Integer i = inicio; i <= termino; i++) {
Recomendo também adicionar checagens se os números são positivos, números negativos estão passando e o programa não diz nada sobre isso.

2022-02-28 11:26 UTC, DanielRosa74 commented on desafio-03/DanielRosa74/java/PalindromicNumbers.java
> +      for (Integer i = inicio; i <= termino; i++) {
Oi, @WashingtonARamos . Fiz as alterações que você solicitou, mas agora a verificação não aceita. Diz que o arquivo inteiro está diferente. Eu, de fato, sobrescrevi o arquivo antes de subir, mas o programa é o mesmo. O que posso fazer para os checks aceitarem o programa?

2022-03-01 03:08 UTC, mpinheir reviewed
Está funcionando mas fica um desafio a mais para ti:
Se o usuário não entrar uma range de números inteiros, não aborte o programa, volte para entrada de dados e fique em um looling até o usuário digitar os valores corretos ou pressionar a tecla esc para abortar o programa. Fica o desafio. Se não quiser fazer o desafio avise que eu aprovo como está.

2022-03-02 18:29 UTC, mpinheir commented
@DanielRosa74 Como discutido. AProvando sem a função do ESC que eu sugeri.

2022-03-02 18:29 UTC, mpinheir approved these changes

2022-03-03 00:27 UTC, WashingtonARamos approved these changes

2022-03-03 00:28 UTC, merged