Desafio 04  com nodejs
OsProgramadores/op-desafios pull request #734
Opened 2022-03-05 14:47 UTC by alleSilva

2022-03-05 20:01 UTC, anthonylgf requested changes
Obrigado pela resolução enviada, segue dois comentários que fiz sobre ela.

2022-03-05 20:01 UTC, anthonylgf commented on desafio-04/alleSilva/javascript/chessBoard.js
> +const countOccurr = (arr) => (val) => arr.reduce((a, v) => (v === val ? a + 1 : a), 0)
Em tese aqui você está utilizando um operador ternário para ver se o valor da peça é o que você que não? Como o desafio pede para não utilizar.

2022-03-05 21:04 UTC, alleSilva commented on desafio-04/alleSilva/javascript/chessBoard.js
> +  console.log("Enter para continuar ou ctrl + d pra finalizar")
Vou olhar essa opção

2022-03-05 21:04 UTC, alleSilva commented on desafio-04/alleSilva/javascript/chessBoard.js
> +const countOccurr = (arr) => (val) => arr.reduce((a, v) => (v === val ? a + 1 : a), 0)
Pode crer, tem um ternário maroto aí

2022-03-05 21:34 UTC, anthonylgf commented on desafio-04/alleSilva/javascript/chessBoard.js
> +const countOccurr = (arr) => (val) => arr.reduce((a, v) => (v === val ? a + 1 : a), 0)
Beleza, repense na sua solução para não utilizar este ternário

2022-03-07 23:05 UTC, anthonylgf approved these changes
Parabéns pela solução, gostei muito da questão de ir mostrado o board a medida que preenchemos o tabuleiro.

Acho que uma melhoria futura é resetar o tabuleiro depois de contarmos as peças e o usuário pedir para continuar.

2022-03-07 23:06 UTC, merged

2022-03-07 23:47 UTC, alleSilva commented
Obrigado! Posso implementar futuramente! Também pensei em preencher o board aleatóriamente é um exercício bom.