Ch02
OsProgramadores/op-desafios pull request #760
Opened 2022-04-07 16:51 UTC by ArchamusBash

2022-04-07 17:05 UTC, marcopaganini approved these changes

2022-04-07 17:05 UTC, marcopaganini requested changes
O nome do diretório da linguagem está errado. Tem que ser `python`, não `python3`.

2022-04-07 17:52 UTC, ArchamusBash commented
Corrigido, obrigado por rever.

2022-04-08 03:19 UTC, marcopaganini approved these changes

2022-04-08 03:19 UTC, merged