New_Answer_Desafio02
OsProgramadores/op-desafios pull request #803
Opened 2022-08-29 00:25 UTC by gabogaldino

Hi! I'm submitting my answer to challenge 2 with the C# language. Thanks!

2022-09-03 14:26 UTC, ThiagoCostaBarbosa commented
@gabogaldino Pre-submit acusou que tu precisa colocar seu arquivo num subdiretório com o nome da linguagem. Ficamos no aguardo dessa alteração

2022-09-18 14:36 UTC, gabogaldino commented
Atualizei, e agora?

2022-09-18 18:32 UTC, marcopaganini commented
Eu dei uma olhada e você tem um monte de arquivos auto gerados, cache etc. Por favor envie apenas o código fonte.

2022-09-19 22:24 UTC, gabogaldino commented
Olá! Perdão, não tinha olhado a árvore. E agora?

2022-09-21 03:55 UTC, WashingtonARamos requested changes
Apenas dois pontos e uma dica. De resto está tudo ok.

2022-09-21 03:55 UTC, WashingtonARamos commented on desafio-02/gabrielgaldino/csharp/Desafio_02_csharp.cs
> +}
Esta chave extra não é necessária, você pode remove-la. Pode também aproveitar e recuar a indentação do código.

2022-09-21 03:55 UTC, WashingtonARamos commented on desafio-02/gabrielgaldino/csharp/Desafio_02_csharp.cs
> +﻿    namespace csharp
Você não listou ao começo do arquivo os namespaces utilizados durante a execução. Está faltando System e System.Collections.Generics

2022-09-21 03:55 UTC, WashingtonARamos commented on desafio-02/gabrielgaldino/csharp/Desafio_02_csharp.cs
> +                List<int> numeros = new List<int>();
Dica: você pode utilizar inferência de tipo para deixar o código mais curto e legível, esta linha ficaria assim:
`var numeros = new List<int>();`
O mesmo pode ser aplicado `primos`.

2022-10-03 23:51 UTC, gabogaldino commented
Olá! Obrigado pela orientação e sugestão! Atualizei o código:

2022-10-03 23:52 UTC, gabogaldino reviewed
Atualização:

2022-10-16 23:01 UTC, WashingtonARamos approved these changes

2022-10-16 23:01 UTC, merged