Desafio 2 em Java.
OsProgramadores/op-desafios pull request #873
Opened 2022-11-13 22:46 UTC by leonelsanchesdasilva

2022-11-20 13:42 UTC, anthonylgf requested changes

2022-11-20 13:42 UTC, anthonylgf commented on desafio-02/leonelsanchesdasilva/java/desafio02.java
> +    for (int i = 1; i <= 10000; i++) {
O teu programa está imprimindo o 1 como primo. Inicie o loop a partir de 2 que irá consertar isto

2022-11-20 13:42 UTC, anthonylgf commented on desafio-02/leonelsanchesdasilva/java/desafio02.java
> +      Boolean primo = true;
Ao invés de utilizar um objeto, seria melhor usar uma variável primitiva: `boolean`, o funcionamento do código é o mesmo

2022-11-28 02:06 UTC, MatMercer commented
Fechando pois corrigir múltiplas linguagens custa muito tempo.

Resolva o desafio pela pull request #870

2022-11-28 02:06 UTC, closed without merging