Desafio 02 - lgrando1
OsProgramadores/op-desafios pull request #914
Opened 2022-12-16 00:25 UTC by lgrando1

2022-12-16 18:05 UTC, lgrando1 reviewed
Tentei criar um outro PR com a solução do desafio 03, mas acabei me enrolando. Reverti o commit e subi novamente o código do desafio 02. Assim que este PR for aprovado, solicito novamente com a solução do desafio 3. Obrigado.

2022-12-17 16:31 UTC, WashingtonARamos requested changes
@lgrando1 por favor, modifique o caminho da pasta onde você está salvando seu arquivo *.py para /python/ (com 'p' minúsculo) invés de /Python/ (com 'P' maiúsculo)

2022-12-17 17:06 UTC, lgrando1 commented
Pode deixar, @WashingtonARamos farei isto. Já subo a versão atualizada. Obrigado

2022-12-17 19:55 UTC, lgrando1 commented
> @lgrando1 por favor, modifique o caminho da pasta onde você está salvando seu arquivo *.py para /python/ (com 'p' minúsculo) invés de /Python/ (com 'P' maiúsculo)

@WashingtonARamos acabei de realizar a mudança. muito obrigado.

2022-12-18 04:03 UTC, WashingtonARamos approved these changes
Parece bom, mergeando

2022-12-18 04:04 UTC, merged