Resolução desafio 14 por Valdinei Junior
OsProgramadores/op-desafios pull request #926
Opened 2023-01-13 22:14 UTC by ValdineiJunior

Parar rodar o programa basta usar "node desafio14.js" utilizando a versão mais recente do node, teste feito na v18.13.0.

2023-01-16 17:15 UTC, anthonylgf requested changes

2023-01-16 17:15 UTC, anthonylgf commented on desafio-14/valdineijunior/javascript/desafio14.js
> +readNumericalExpressions("./d14.txt");
A única coisa que mudaria no desafio seria receber esse nome do arquivo do usuário que está executando o código, na hora que o código que está executando.

E removeria o arquivo do d14.txt da solução

2023-01-16 20:00 UTC, ValdineiJunior commented on desafio-14/valdineijunior/javascript/desafio14.js
> +readNumericalExpressions("./d14.txt");
Obrigado pelo feedback, alterei o código, se entendi corretamente o usuario escolhe o arquivo de entrada.
Agora pra executar é necessario usar.
$ node desafio14.js (nome_do_arquivo)

2023-01-17 02:18 UTC, mpinheir commented
@ValdineiJunior testei com: node desafio14.js d14.txt

Versão de NodeJS: Node.js v18.12.1

**resultado:**

node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at node:path:1082:24
    at Object.resolve (node:path:1096:39)
    at resolveMainPath (node:internal/modules/run_main:19:40)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:75:24)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

2023-01-17 09:13 UTC, ValdineiJunior commented
Passei a instrução errada, como eu retirei o arquivo d14.txt do diretório.
É preciso fazer o download do arquivo txt e utilizar:
$ node desafio14.js (caminho_do_arquivo)

2023-01-22 00:54 UTC, mpinheir approved these changes

2023-01-22 00:55 UTC, mpinheir approved these changes

2023-01-22 01:18 UTC, anthonylgf approved these changes

2023-01-22 01:19 UTC, merged