Desafio 03 em JS
OsProgramadores/op-desafios pull request #936
Opened 2023-01-23 02:20 UTC by jorge-tarin

2023-01-24 03:43 UTC, mpinheir commented
@jorge-tarin expanda sua solução para permitir passar dois números por linha de comando (tipo num inicial e número final de um range) e ai exiba os palindromes entre estes números. Estou complicando um pouco te aprendizado mas acho que vai ser bom.

2023-01-24 04:00 UTC, mpinheir requested changes
Altere por favor a solução para pedir a range de números e mostre os paramêtros entre a e b inclusive. Obrigado

2023-01-30 01:45 UTC, MatMercer approved these changes
```sh
$ node desafio-03/jorge-tarin/javascript/desafio.js "00000" "999999"
0
1
2
3
4
5
6
7
8
9
11
...
994499
995599
996699
997799
998899
999999
```

🌟 🚀

2023-02-07 16:54 UTC, anthonylgf requested changes

2023-02-10 01:31 UTC, jorge-tarin commented
@anthonylgf, correção sugerida aplicada.

2023-02-10 01:31 UTC, anthonylgf approved these changes

2023-02-10 02:13 UTC, mpinheir approved these changes

2023-02-10 02:13 UTC, merged