Primos em python
OsProgramadores/op-desafios pull request #944
Opened 2023-02-05 16:52 UTC by lucasfturos

2023-02-14 15:54 UTC, anthonylgf requested changes

2023-02-14 15:54 UTC, anthonylgf commented on desafio-08/lucasfturos/python/fracoes.py
> +from fractions import Fraction
Bom dia, conseguiria resolver o desafio, só que sem utilizar essa biblioteca externa?

O código está correto e funcionando, mas essa biblioteca já realiza algumas operações, como reduzir a fração e soltar o erro quando a divisão é por zero.

E um dos objetivos do desafio é pensar como fazer esse processamento manualmente.

2023-02-14 16:41 UTC, lucasfturos commented on desafio-08/lucasfturos/python/fracoes.py
> +from fractions import Fraction
Certo, vou fazer o método manual. Eu fiz desta maneira para mostrar um jeito mais simples de resolver. Logo mandarei do jeito manual.

2023-02-15 23:03 UTC, anthonylgf approved these changes

2023-02-15 23:03 UTC, merged