Solucao desafio 13 por Valdinei Junior
OsProgramadores/op-desafios pull request #946
Opened 2023-03-11 20:59 UTC by ValdineiJunior

Para executar a solução utilize:

node desafio13 a1

podendo substituir a notação a1 por uma de sua preferencia.

versão do node utilizada v18.13.0

2023-03-15 19:20 UTC, anthonylgf requested changes
@ValdineiJunior eu executei o teu programa utilizando o a1 como parâmetro aqui, ficaram algumas horas rodando e ele ainda não tinha finalizado, não cheguei a ver se entrou em algum loop infinito.

Eu estou utilizando a versão do node que utilizou, a `18.13`. Tentei trocar a casa de início e mesmo assim dá na mesma, demora várias horas e não aparecem os resultados.

2023-03-15 19:43 UTC, ValdineiJunior commented
Deixa eu verificar novamente, a solução executa em segundos. Se demorar algo mais que um minuto não precisa aguardar. Pelo jeito quebrei algo ao formatar para o envio. Estou revisando e volto a atualizar a solução.

2023-03-15 22:19 UTC, ValdineiJunior commented
Pelo que verifiquei não enviei a versão final do programa @anthonylgf , veja agora se consegue executar. A execução em alguns casos levam um pouco mais de tempo, mas não passam de 30segundos.

2023-03-16 10:34 UTC, anthonylgf approved these changes
Está aprovado, sugiro depois testar o programa com as casas g7, g6 e g3 como parâmetro de entrada, são as que demoram mais para serem executadas no código. Parabéns pela solução!

2023-03-16 10:35 UTC, merged