Terminado desafio02 em csharp
OsProgramadores/op-desafios pull request #954
Opened 2023-04-15 03:56 UTC by ronaldofas

Concluído desafio 02 em csharp por ronaldofas

2023-04-19 17:32 UTC, anthonylgf requested changes

2023-04-19 17:32 UTC, anthonylgf commented on desafio-02/ronaldofas/csharp/numero_primos.cs
> +        List<int> linha = new List<int>();
O teu programa está dando erro na hora de compilar. Não está esquecendo de importar/utilizar alguma diretiva que é necessária para o programa.

O erro que aparece é o seguinte:
```
prime.cs(54,38): error CS0246: The type or namespace name `List' could not be found. Are you missing `System.Collections.Generic' using directive?
```

2023-04-30 18:46 UTC, ronaldofas commented
Tudo certo agora?

2023-05-04 01:11 UTC, anthonylgf requested changes
Ainda está aparecendo um erro para mim:

```
prime.cs(68,51): error CS1061: Type `System.Collections.Generic.List<int>' does not contain a definition for `Max' and no extension method `Max' of type `System.Collections.Generic.List<int>' could be found. Are you missing `System.Linq' using directive?
```

Acho que é só adicionar no começo um `using System.Linq;` eu acho que conserta

2023-05-11 03:40 UTC, mpinheir commented
@ronaldofas você vai dar continuidade ao desafio?

2023-05-11 17:42 UTC, ronaldofas commented
Sim vou, é que essa semana estou com problemas, vou tentar fazer entre amanhã e sábado

2023-05-28 23:55 UTC, closed without merging