desafio-06 pedroexpedito em cpp
OsProgramadores/op-desafios pull request #956
Opened 2023-04-24 16:45 UTC by PedroExpedito

2023-05-11 03:39 UTC, mpinheir commented
@PedroExpedito o seu programa está pedindo seguinte quando excutado:
Use:
 ./foo palavra words.txt

Se eu digito ./foo palavra word.txt nada acontece.
Sim, assuma que eu compilei e gerei o binárioo como ./foo

Eu também não acho que seu programa está fazendo que está escrito no enunciado do desafio.
Note que bastaria passar uma palavra como parâmetro e poder gerar os anagrams.
Verifique por favor.
Obrigado!

2023-05-12 14:08 UTC, PedroExpedito commented
O primeiro argumento é a palavra para gerar os anagramas, e o segundo argumento é o dicionário(arquivo).

Verifiquei aqui o arquivo e está correto, serio que você não obtêm nenhuma mensagem de erro?

2023-05-12 18:32 UTC, anthonylgf requested changes
Pior que eu rodei aqui, compilei o programa, rodei ./foo "palavra1 palavra2 ...." <caminho-absoluto-arquivo-palavras>

E está funcionando corretamente, comparei até o resultado com os de outros desafios. Acho que o @pedroexpedito tinha que só adicionar um README explicando como compilar e como passar os argumentos.

Porque caso a expressão tenha espaço aí tem que passar entre aspas para funcionar, tipo:

./foo palavra1 palavra2 [caminho-arquivo] (Quebra)
./foo "palavra1 palavra2" [caminho-arquivo] (Funciona)

Por mim, adicionando o README explicando esses detalhes de como executar, tá bom, o programa está funcionando

2023-05-12 19:59 UTC, anthonylgf approved these changes

2023-05-12 19:59 UTC, merged