Desafio 07 concluído em Python3.
OsProgramadores/op-desafios pull request #958
Opened 2023-05-01 02:17 UTC by Hoklifter

2023-05-04 01:43 UTC, anthonylgf requested changes

2023-05-04 01:43 UTC, anthonylgf commented on desafio-07/hoklifter/python/unix_tac.py
> +from file_read_backwards import FileReadBackwards as reverse_read
O objetivo dos desafios é tentar fazer as soluções sem pegar algo já pronto.

2023-05-11 03:45 UTC, mpinheir commented
@Hoklifter você vai dar continuidade ao desafio?

2023-05-11 09:32 UTC, Hoklifter commented
> @Hoklifter você vai dar continuidade ao desafio?

Vou sim!

2023-05-28 23:55 UTC, closed without merging