Desafio 07
OsProgramadores/op-desafios pull request #965
Opened 2023-05-27 23:53 UTC by MatMercer

Ignorem por hora, vou adicionar um README.md

2023-08-09 23:56 UTC, marcopaganini requested changes

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +func main() {
Eu normalmente espero a função `main()` estar no final do arquivo, mas o programa não deixa de funcionar por causa disso :)

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +	if len(args) != 1 {
É uma prática melhor primeiro checar o tamanho de os.Args e emitir uma mensagem de erro. Voce aqui seta `args := os.Args[1:]` antes de checar o tamanho. Outra coisa é que eu não usaria uma variável intermediária (args). Ao invés, usaria `os.Args` diretamente (o nome não é ambíguo e fácil de entender do que se trata.)

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +func errAndExit(msg string) {
Essa função é não-standard e desnecessária. Use `log.Fatal`, `log.Fatalln`, ou `log.Fatalf` em todos os lugares onde você chama `errAndExit` e remova essa função.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +	fileName := args[0]
`filename := os.Args[0]`

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +	check(err)
Nooooope :)

Error checking é sempre inline. Lembre-se da regra: Dentro do main, um error failure sai do programa com um `log.Fatal` (se for um erro fatal). Dentro de funções, sempre retorne o erro pro caller, nunca use `log.Fatal` ou saia do programa (a não ser em alguns casos super específicos).

Aqui seria (e em vários outros lugares no código), seria:

```
if err != nil {
    log.Fatal(err)
}
```

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +	check(err)
Use error checking inline.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +func check(e error) {
Essa função é desnecessária (veja comentários abaixo).

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +	b := make([]byte, bufSize)
Variáveis com um caracter são uteis em contextos muito restritos. Exemplo: Num for loop ou quando elas saem de contexto em algumas linhas. Aqui, eleas são usadas bem abaixo, o que dificulta a compreensão.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +	r := NewReverseReader(f, fs)
NewReverseReader is simple enough that you could probably just do `r := &NewReverseReader{f, fs}` and eliminate one more function.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +			// prevent over reading if result is less than buf size
Nit: comentários devem ser uma expressão. Começando com letras maiúsculas e terminando em ponto. (mesmo problema em outros comentários).

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +		check(err)
inline error checking.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +				out(b[i+1 : lastEnd])
Por que uma função chamada `out`? Por que não usar fmt.Println() ao invés?

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +				check(err)
Se voce não usar Write, não precisa checar o erro. E na prática, raramente se checa erro na saída pra stdout.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +// out outputs to os.Stdout checking for errors
Talvez essa função possa morrer...

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +func (r *ReverseReader) Read(b []byte) (n int, err error) {
Voce provavelmente não precisa aceitar um ponter pra ReverseReader. ReverseReader por si só deveria funcionar nesse caso.

2023-08-09 23:56 UTC, marcopaganini commented on desafio-07/MatMercer/go/README.md
> +sudo cgcreate -t $USER:$USER -a $USER:$USER -g memory:"$CGROUP"
Nota: cgcreate não é disponível imediatamente em várias distros. No debian, `apt-get install cgroup-tools`

2023-08-12 18:35 UTC, MatMercer commented on desafio-07/MatMercer/go/tac.go
> +				out(b[i+1 : lastEnd])
por conta de performance, o fmt.Println é unbuffered, olha o tamanho da diferença q dá se eu usar fmt.Print:

usando buffered writer
```
$ time ./tac-buf 1GB.txt > out-buf.txt

real  0m1.396s
user  0m0.721s
sys   0m0.671s
```

usando fmt.Print
```
$ time ./tac-unbuf 1GB.txt > out-unbuf.txt

real  0m17.880s
user  0m6.485s
sys   0m11.538s
```

check para saber se são iguais:

```
$ md5sum out-buf.txt out-unbuf.txt correct-out.txt
2b4fd25f11d75c285ec69ecac420bd07  out-buf.txt
2b4fd25f11d75c285ec69ecac420bd07  out-unbuf.txt
2b4fd25f11d75c285ec69ecac420bd07  correct-out.txt
```

vc pode encontrar essa versão unbuffered do tac.go em `git checkout 75953502ecccfd7af84d06c3d4a982dce923a5e2`

2023-08-12 18:37 UTC, MatMercer commented on desafio-07/MatMercer/go/tac.go
> +				check(err)
como vou continuar usando write, vou ignorar o erro simplesmente

2023-08-12 18:55 UTC, MatMercer commented on desafio-07/MatMercer/go/tac.go
> +func (r *ReverseReader) Read(b []byte) (n int, err error) {
`r.offset -= int(len(b))` faz eu precisar de um pointer receiver

2023-08-13 03:39 UTC, marcopaganini commented on desafio-07/MatMercer/go/tac.go
> +				out(b[i+1 : lastEnd])
Sim, isso é verdade. O fmt.Print* é lento comparado com o Buffer.

2023-08-13 03:40 UTC, marcopaganini approved these changes

2023-08-13 03:40 UTC, merged