meu desafio 2 em python
OsProgramadores/op-desafios pull request #981
Opened 2023-07-02 20:08 UTC by JonataMSilva

2023-07-14 02:41 UTC, ValdineiJunior commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +
As três primeiras linhas podem ser retiradas sem perda.

2023-07-14 02:43 UTC, ValdineiJunior commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +    """funcao para encontrar o numero primo"""
Esse comentario pode ser excluido se optar por alterar o nome da função, dizendo o que ela faz exemplo "def encontra_num_primo(numero):"

2023-07-14 02:49 UTC, ValdineiJunior commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +    for i in range(1, 10000):
Nessa linha você poderia optar por alterar o valor 10000 para o próprio número + 1, assim evitaria divisões desnecessarias, exemplo: 10 / 11, 10 / 12, 10 / 13 .....
Note que quando utilizamos range(valor inicial, valor final) o valor final não é incluido por isso o número + 1, assim a última comparação seria o número por ele mesmo.

2023-07-14 02:52 UTC, ValdineiJunior commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +        return 1
Como retorno da função, poderia optar para True caso tenha dois divisores, e False caso contrario. Só seria necessario um ajuste na linha 16 que ficaria desta forma:
if num_primo(primos):
Como o retorno sera verdadeiro ou falso não é preciso uma comparação.

2023-07-14 22:57 UTC, ValdineiJunior commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +def encontrar_num_primo(numero):
Agora que fez as alterações percebi, que essa função poderia ser melhor nomeada. Quanto mais descritivo for suas funções e seu código melhor sera entendido por vc ou por outros. No caso aqui o que a função esta fazendo vc passa um numero pra ela. E o que ela faz ?

2023-07-14 23:01 UTC, ValdineiJunior commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +for primos in range(1, 10000):
Neste trecho aqui quando definido "primos" in range, não necessariamente o número sera um primo pode ser ou não ser, então acredito que ficaria mais descritivo utilizar numero in range. faz sentido ?

2023-07-26 01:23 UTC, ValdineiJunior requested changes
Surigo uma alteração no nome da função encontrar_num_primo, para "verifica se número é primo". Só para ficar mais descritivo.
E na linha:
for primos in range(1, 10000), sugiro alterar "primos" para "números".
Se me responder ou fizer alterações nesse sentido aprovo a PR.

2023-07-26 02:31 UTC, JonataMSilva commented
feito as alterações no pull request  @ValdineiJunior

2023-07-26 02:44 UTC, ValdineiJunior approved these changes

2023-07-27 11:40 UTC, ValdineiJunior commented
Jonata cometi alguns erros na correção da sua PR.
Da forma que ficou dará erro to linter por "numero" já ser utilizado na primeira função.
Peço desculpa, mas tera que voltar para primo ou outro nome dentro do for.
O outro erro foi que pedi pra retirar os comentarios do inicio e dentro da função, e aparentemente é obrigatório em python.
Vai precisar inserir os dois comentarios novamente, sugiro algo como isso:

"Programa para listar todos os números primos entre 1 e 10000"

def verifica_se_numero_eh_primo(numero):
    "funcao para verificar se o numero é primo"

Depois de alterado utilize o lint do site [Lint](https://lint.osprogramadores.com/t/form.html) , selecione a linguagem python, cole sua solução e de um submit, ele verifica sua solução se tiver algum erro ele vai apontar os erros.

Esse mesmo teste é rodado automatico antes  da PR ser aprovada, por isso não passou na aprovação.

2023-07-27 21:45 UTC, JonataMSilva reviewed
feito as correções

2023-07-27 22:18 UTC, ValdineiJunior approved these changes

2023-07-28 02:27 UTC, ValdineiJunior commented
@JonataMSilva outra alteração proposta pelo @mpinheir foi a retirada da divisão por 1 a cada iteração, isso vai economizar recurso e deixar o programa mais rápido.
Outra sugestão nesse sentido seria, implementar uma verificação inicial antes do for verificando se o número é divisivel por 2.
caso ele seja já pode retornar falso pois não é um número primo.
Essas duas alterações deixaram o programa mais performatico, se quiser até testar posteriormente as duas versões verá a diferença.
Qualquer dúvida nesse sentido só chamar.

2023-07-28 03:27 UTC, mpinheir requested changes

2023-07-28 23:07 UTC, JonataMSilva commented on desafio-02/JonataMSilva/python/numeros_primos.py
> +    for i in range(1, 10000):
pesquisei mais sobre o crivo de erástostenes, tive um pouco de dificuldade para entender a logica. mas irei refazer o codigo usando o crivo de erástostenes

2023-07-29 14:09 UTC, mpinheir approved these changes

2023-07-29 14:19 UTC, merged