Desafio 10
OsProgramadores/op-desafios pull request #985
Opened 2023-07-16 21:21 UTC by MatMercer

# Solução desafio 10

Para rodar, é necessário ter os seguintes programas:

* go
* wget
* make

Basta rodar esse comando para executar o programa:

```bash
# modo normal
make run
# modo debug
make run-debug
```

2023-08-13 04:35 UTC, marcopaganini requested changes

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +	if len(os.Args) != 2 {
Por que não usar log.Fatal* (que já manda pra stderr, se bem me lembro). Voce pode criar um outro objeto pra casos especiais como é o caso de debug abaixo.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +	if strings.ToLower(os.Getenv("DEBUG")) == "true" {
Normalmente, em Go evita-se o "else" (é idiomático). Sendo assim, voce pode por exemplo inicializar o debug pra ser `log.New(io.Discard, "", 0)` e depois se DEBUG estiver definido como true, fazer o override.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +	err := runPrograms(fileName)
Como voce não retorna mais nada de runPrograms, pode simplificar isso assim:

```
if err := runPrograms(filename); err != nil {
  log.Fatalf("Turing machine error: %v", err)
}
```

Outro detalhe é que quando voce retorna uma mensagem de erro, ela sempre começa em lowercase (porque pode ser apendada a alguma coisa), mas quando faz o log.Fatal*, começa com uppercase.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +		if len(text) == 0 {
Ainda que não seja pedido, é talvez uma chance de suportar comentários. Se a linha começar com '#', ignore...

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +		if !(len(text) == 0) && len(progAndInput) != 2 {
Eu estou tendo um pouco de dificuldade de parsar essa linha.

1) Por que voce usou `!(len(text) == 0)` ao invés de `len(text) != 0`?
2) Voce já chegou se len(text) == 0 acima e dá o continue. Por que testar de novo aqui?

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +	fileScanner := bufio.NewScanner(f)
Se você quiser evitar toda essa confusão do Scanner, uma opção é usar o ReadFile e ler o arquivo inteiro em memória (assumindo que é um programa e cabe em memória). Ai é só fazer o split em newlines. e voce tem o arquivo inteirinho num slice.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +func New(progFileName string, input string, debug *log.Logger) (*TuringMachine, error) {
Toda função exportada tem que ter um comentário no formato:
// New creates a new turing machine.

Obs: Voce tem o `golangci-lint` instalado? Eu recomendo. Ele pega vários desses detalhes.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +func New(progFileName string, input string, debug *log.Logger) (*TuringMachine, error) {
Um outro detalhe importante é que apesar de ser meio "estranho", sempre é preferível passar um io.Reader ao invés de um filename. Isso torna o teste mais fácil. Mas é opcional.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +	prog := make(program)
Normalmente só se usa `make` pra tipos simples ou arrays, onde não se consegue usar algo tipo `prog := &program{}`

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +		// ignore comments
:+1:

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +			return nil, fmt.Errorf("invalid syntax at line %d, expected 5 tokens, got %d: '%s'", line, len(tokens), text)
Ao invés de `'%s'`, use `%q` que já faz o quoting automaticamente.

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +			return nil, fmt.Errorf("invalid direction at line %d: '%s' -> must be one of l,r,*", line, d)
Idem aqui (%q).

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +			prog[targetState] = make(map[symbol]programEntry)
Idem aqui (make)

2023-08-13 04:35 UTC, marcopaganini commented on desafio-10/MatMercer/go/machine/machine.go
> +		m.debug.Printf("cur: %c:%d\n", currentSymbol, currentSymbol)
Isso é um dos infernos do Go: Ter que ficar passando `debug` objects pra tudo que é objeto.

Uma alternativa que eu encontrei é usar um pacote simples de logging (tem milhões deles, cada um mais complicado do que o outro), chamado `rlog` (github.com/romana/rlog). Esses caras já fazem pra voce o esquema de logar só se uma variável de environment estiver setada e voce não precisa ficar passando pra todo lado, já que a variável de ambiente é externa ao programa.

2023-08-13 16:43 UTC, MatMercer commented on desafio-10/MatMercer/go/machine/machine.go
> +		m.debug.Printf("cur: %c:%d\n", currentSymbol, currentSymbol)
Sim em Go é complicado isso mesmo, no trabalho pra serviços web a gente usa ctx, é oq a lib google cloud faz, aí vira:

logger.Info(ctx, "%s", param...)

Até pq vc quer saber qual http request um log está atrelado, por conta do open telemetry, tudo fica no ctx e o logger.XX se encarrega de extrair as coisas do ctx.

Por se tratar de um exercício simples vou acabar deixando assim, até pq debug é usado somente em um lugar dentro da machine e gostei do app ficar sem nenhuma dependência de libs.

2023-08-13 16:47 UTC, MatMercer commented on desafio-10/MatMercer/go/machine/machine.go
> +func New(progFileName string, input string, debug *log.Logger) (*TuringMachine, error) {
Gostei da ideia de passar io.Reader

2023-08-13 16:57 UTC, MatMercer commented on desafio-10/MatMercer/go/machine/machine.go
> +			return nil, fmt.Errorf("invalid syntax at line %d, expected 5 tokens, got %d: '%s'", line, len(tokens), text)
nossa eu vou usar isso mto daqui por diante... tô até vendo ahhaah

2023-08-13 17:04 UTC, MatMercer commented on desafio-10/MatMercer/go/main.go
> +		if !(len(text) == 0) && len(progAndInput) != 2 {
Esqueci de tirar após refactor provavelmente

2023-08-13 17:06 UTC, MatMercer commented on desafio-10/MatMercer/go/main.go
> +	fileScanner := bufio.NewScanner(f)
Usei scanner por conta das tratativas q ele tem automáticas do new line do Windows e lines não terminados.

```
// ScanLines is a split function for a Scanner that returns each line of
// text, stripped of any trailing end-of-line marker. The returned line may
// be empty. The end-of-line marker is one optional carriage return followed
// by one mandatory newline. In regular expression notation, it is `\r?\n`.
// The last non-empty line of input will be returned even if it has no
// newline.
func ScanLines(data []byte, atEOF bool) (advance int, token []byte, err error) {
	if atEOF && len(data) == 0 {
		return 0, nil, nil
	}
	if i := bytes.IndexByte(data, '\n'); i >= 0 {
		// We have a full newline-terminated line.
		return i + 1, dropCR(data[0:i]), nil
	}
	// If we're at EOF, we have a final, non-terminated line. Return it.
	if atEOF {
		return len(data), dropCR(data), nil
	}
	// Request more data.
	return 0, nil, nil
}

```

2023-08-13 17:10 UTC, MatMercer commented on desafio-10/MatMercer/go/main.go
> +	if len(os.Args) != 2 {
Foi nitpick da minha parte, mas é pq o default adicionar data e horário:

2023/08/13 14:08:39 programs file required, usage: ./turing [programs file]

2023-08-13 17:12 UTC, MatMercer commented on desafio-10/MatMercer/go/main.go
> +	err := runPrograms(fileName)
Eu desconhecia totalmente essa questão de precisar ser uppercase, mto interessante

2023-08-16 00:58 UTC, marcopaganini commented on desafio-10/MatMercer/go/main.go
> +	if len(os.Args) != 2 {
Ah, voce tem duas escolhas. Pode remover isso com `log.SetFlags(0)` antes de tudo, ou melhor, cria uma função "usage()" que só mostra o usage e sai do programa (é uma das exceções em relação a funções saindo do programa). Essa função pode mandar direto pra stderr.

2023-08-16 00:58 UTC, marcopaganini approved these changes
:+1:

2023-08-16 00:58 UTC, merged