Challenge 02 solved! User: kaetaen.
OsProgramadores/op-desafios pull request #988
Opened 2023-07-27 00:31 UTC by kaetaen

Resolução do desafio 02 pelo usuário @kaetaen

2023-07-27 02:46 UTC, ValdineiJunior approved these changes

2023-07-27 02:56 UTC, ValdineiJunior requested changes
Sua solução esta incluindo o número 1, que não é primo. Precisa tratar ele.

2023-07-27 03:06 UTC, kaetaen commented
> Sua solução esta incluindo o número 1, que não é primo. Precisa tratar ele.

Ok

2023-07-27 11:57 UTC, ValdineiJunior commented
Na aprovação dos desafios é rodado alguns testes automáticos para verificar se seu código esta no padrão correto.
Utilize o Lint do site antes de enviar a solução [Linte](https://lint.osprogramadores.com/t/form.html) escolha a linguagem , cole o código e clique em submit. E corrijá os eventuais erros.

Qualquer dúvida fico a disposição.

2023-07-27 13:00 UTC, kaetaen commented
Bom dia @ValdineiJunior , fiz a correção ✨

2023-07-29 14:14 UTC, ValdineiJunior commented
@kaetaen sugiro utilizar o lint do site https://lint.osprogramadores.com/t/form.html para procurar por erros e sintaxes corretas de acordo com nosso projeto. Passei nele e retornaram os seguintes errros.

[pylint] Line 14 Col 0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
[pylint] Line 17 Col 0: C0303: Trailing whitespace (trailing-whitespace)

O primeiro é um parenteses desnecessario no if e o segundo são espaços em branco ná linha 17, esses espaços em branco são bem sutis dificil de encontrar olhando para o código principalmente em projetos maiores, mas essas ferramentas nos ajudam a encontra-los. E evitar futuros bugs no nosso programa.

No mais o código ta bacana !

2023-08-16 23:55 UTC, closed without merging